// e2e/fixtures.ts — deterministic test-environment setup for the Reframe GUI E2E.
//
// Builds a throwaway, per-run data root and seeds it with ONE real sample video
// so the launched Electron app shows a library entry to open + preview. Nothing
// here mocks the app: the sample is a genuine H.264/AAC MP4 generated by ffmpeg,
// and it is registered through the SAME `library.add` JSON-RPC the running app
// would call (driven against the real Python sidecar), so `media.playable`
// resolves it to the source path and the mstream protocol streams real bytes.
//
// Why seed out-of-band instead of clicking "Add videos": the add path goes
// through a NATIVE OS file dialog (dialog.openVideos). Seeding the data root the
// sidecar reads is equivalent for everything DOWNSTREAM of the add — the app
// lists + opens + plays the exact same library record either way.
//
// SCOPE CORRECTION (v1.5 e2e-coverage lane). This header used to say that path
// "cannot be driven headlessly" and that seeding is "equivalent", full stop. Both
// were wider than the evidence, and the gap they hid was real: only the OS WIDGET
// is undrivable, not the chain around it (button -> Library.handlePick -> the
// preload `window.api.openVideos` -> `ipcMain.handle('dialog.openVideos')` ->
// dialog.showOpenDialog -> `library.add`), and that chain had ZERO end-to-end
// coverage — a broken preload wiring would have shipped green behind the
// "Native file picker unavailable" toast Library.tsx degrades to.
// `add-videos-dialog.spec.ts` now drives it by replacing `dialog.showOpenDialog`
// INSIDE the running main process (electron-playwright-helpers `stubDialog`), so
// every other link is the real one. Seeding stays the right DEFAULT for the other
// specs — it is faster and it is not what they are testing — rather than the only
// option available.

import { spawn, spawnSync } from 'node:child_process';
import {
  mkdtempSync,
  existsSync,
  readFileSync,
  readdirSync,
  realpathSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { findLatestBuild, parseElectronApp } from 'electron-playwright-helpers';

// ESM (the app package is "type": "module"): derive __dirname from import.meta.
const HERE = dirname(fileURLToPath(import.meta.url));

/** Absolute path to the repo root (two levels up from app/e2e). */
export const REPO_ROOT = resolve(HERE, '..', '..');
/** The Python sidecar package dir (cwd for `-m media_studio`). */
export const SIDECAR_DIR = join(REPO_ROOT, 'sidecar');
/** The built main-process entry the launched Electron app boots (DEV build). */
export const MAIN_ENTRY = join(REPO_ROOT, 'app', 'out', 'main', 'main.js');
/** electron-builder packaged-artifact output dir (electron-builder.yml). */
export const DIST_DIR = join(REPO_ROOT, 'dist');

/**
 * Env var naming an app that is already INSTALLED on this machine — the escape
 * hatch out of `DIST_DIR`.
 *
 * Until it existed, `findBuiltApp()` could resolve a package from exactly one
 * place (`dist/win-unpacked` and friends), so every "packaged" assertion in this
 * harness was really about the electron-builder OUTPUT tree. Nothing had ever
 * driven an app laid down by the NSIS installer.
 *
 * Accepts "the app itself" in either shape: a Windows `<install dir>/<Product>.exe`
 * or a macOS `<Product>.app` bundle. It NO LONGER simply forwards to
 * `parseElectronApp` — that helper picks the app by scanning the PARENT directory,
 * which mis-resolves both shapes in their real install locations; see
 * `resolveInstalledApp` for the measurement and what replaced it.
 *
 * Consumers: `installed-app.spec.ts` (which self-skips when it is unset) and
 * `findBuiltApp.test.ts` (the deterministic resolution proof).
 */
export const APP_EXE_ENV = 'RF_E2E_APP_EXE';

/**
 * What the launched app boots: the args + (for a real package) the executable
 * path, plus whether we are pointing at a PACKAGED artifact or the dev build.
 */
export interface BuiltApp {
  /** Launch args ([appInfo.main] for a package, [MAIN_ENTRY] for dev). */
  main: string;
  /** electron-builder executable path; undefined => use the dev electron bin. */
  executablePath?: string;
  /** True when resolved to a real electron-builder package (the shipped .exe). */
  packaged: boolean;
}

/**
 * Resolve an app that is already INSTALLED, from :data:`APP_EXE_ENV`.
 *
 * Two deliberate choices, both of them the difference between a proof and a
 * plausible-looking green:
 *
 *  * **FAIL LOUD, never fall back.** A typo'd or stale `RF_E2E_APP_EXE` must not
 *    quietly resolve the dev build; an "installed-build" leg reporting green
 *    while it drove `out/main/main.js` is worse than no leg at all.
 *  * **The CALLER's target is authoritative — for BOTH shapes.**
 *    `parseElectronApp` resolves an app by stripping the argument to its PARENT
 *    directory and then scanning that directory: `readdirSync(dir).find((f) =>
 *    f.endsWith('.exe'))` on Windows — "assume the executable is the only .exe
 *    file in the directory" in its own comment — and the identical
 *    `readdirSync(dir).find((f) => f.endsWith('.app'))` on macOS
 *    (node_modules/electron-playwright-helpers/dist/find_parse_builds.js:
 *    `buildDir = dirname(...)` at :124-131, the two `find` calls at :205-207 and
 *    :239-241). Neither directory is the single-app directory it assumes:
 *    an electron-builder NSIS install dir has `Uninstall <ProductName>.exe`
 *    beside the app (`nsis.oneClick: false`), and the canonical macOS install
 *    location is `/Applications`, which holds every other app on the machine.
 *    Which entry that `find` returns is readdir-order-dependent.
 *
 *    SCOPE CORRECTION (refuted 2026-08-11): this used to harden ONLY the `.exe`
 *    branch and hand `.app` straight back to `info.executable`, on the stated
 *    reasoning that "a macOS `.app` argument is a bundle DIRECTORY rather than an
 *    executable, so there the derived `info.executable` is the right answer".
 *    The premise is true and the conclusion did not follow: the derived value is
 *    only right if `find` chose the bundle the caller named. MEASURED — with a
 *    sibling `Aardvark.app` in the same parent, asking for `Reframe.app` returned
 *    `Aardvark.app/Contents/MacOS/Aardvark` for the executable AND `Aardvark`'s
 *    entry for `main`, silently (nothing throws; the result is well-formed and
 *    wrong). Worse than the Windows twin, because on darwin the chosen bundle
 *    drives `main` too, whereas the win32 branch derives `main` from
 *    `join(buildDir, 'resources')` and so is immune (find_parse_builds.js:246).
 *    Pinned by the sibling-decoy cases in `findBuiltApp.test.ts`.
 *
 *    So: for `.exe` keep the caller's path and borrow only `info.main` (immune,
 *    above); for `.app` derive BOTH from inside the named bundle and never call
 *    `parseElectronApp` at all. A prefix-remap of its answer would NOT do — the
 *    sibling can have a different inner executable name and a different
 *    asar-vs-plain `Resources/app` shape, so the remapped path need not exist.
 */
function resolveInstalledApp(target: string): BuiltApp {
  if (!existsSync(target)) {
    throw new Error(
      `${APP_EXE_ENV} points at a path that does not exist: ${target} — refusing to fall ` +
        'back to the dev build. Pass the INSTALLED app itself (Windows: the ' +
        '<install dir>/<Product>.exe; macOS: the <Product>.app bundle).',
    );
  }
  // Suffix tests on a STRING, not a filesystem case-fold: `.toLowerCase()` here
  // asks "was this argument spelled as an .exe/.app", which is the same question
  // on NTFS and on ext4. (A `normcase`-style probe would be the wrong instrument —
  // nothing about this decision depends on how the FS compares names.) Keeping it
  // suffix-driven rather than `process.platform`-driven is also what lets the
  // darwin arm be exercised on a Linux/Windows CI runner.
  const spelled = target.toLowerCase();
  if (spelled.endsWith('.app')) return resolveMacBundle(target);
  let info: { main: string; executable: string };
  try {
    info = parseElectronApp(target);
  } catch (err) {
    throw new Error(
      `${APP_EXE_ENV}=${target} is not a launchable Electron app tree ` +
        `(expected a sibling resources/app.asar or resources/app): ${(err as Error).message}`,
    );
  }
  const executablePath = spelled.endsWith('.exe') ? target : info.executable;
  return { main: info.main, executablePath, packaged: true };
}

/**
 * Resolve a macOS `<Product>.app` bundle using ONLY paths under that bundle.
 *
 * Mirrors what `parseElectronApp` does for darwin (find_parse_builds.js:211-226)
 * with the one difference that is the whole point: the bundle root is the one the
 * caller named, never `readdirSync(parent).find(...)`.
 */
function resolveMacBundle(bundle: string): BuiltApp {
  const macosDir = join(bundle, 'Contents', 'MacOS');
  const resourcesDir = join(bundle, 'Contents', 'Resources');
  let entries: string[];
  try {
    entries = readdirSync(macosDir);
  } catch (err) {
    throw new Error(
      `${APP_EXE_ENV}=${bundle} is not a launchable Electron app tree ` +
        `(no Contents/MacOS inside the bundle): ${(err as Error).message}`,
    );
  }
  // electron-builder names the inner binary after productName, i.e. the bundle
  // stem — prefer that exact match. Fall back to a lone entry (what
  // parseElectronApp assumes unconditionally), and REFUSE to guess when there are
  // several and none matches: a wrong executable is the failure this whole
  // function exists to prevent, so guessing here would reintroduce it.
  const stem = basename(bundle).replace(/\.app$/i, '');
  const inner = entries.includes(stem) ? stem : entries.length === 1 ? entries[0] : undefined;
  if (inner === undefined) {
    throw new Error(
      `${APP_EXE_ENV}=${bundle}: cannot tell which of Contents/MacOS/[${entries.join(', ')}] ` +
        `is the app binary (none is named "${stem}") — refusing to guess.`,
    );
  }
  const asarPath = join(resourcesDir, 'app.asar');
  const plainPkg = join(resourcesDir, 'app', 'package.json');
  let entry: string | undefined;
  let main: string;
  if (existsSync(asarPath)) {
    // `@electron/asar` is electron-playwright-helpers' OWN declared dependency
    // (^3.2.4) — the very module it reads the archive with — so it is present
    // wherever that helper is. Required LAZILY so a Windows-only run never loads
    // it and a hoisting change can only ever break the darwin arm, loudly.
    const { extractFile } = createRequire(import.meta.url)('@electron/asar') as {
      extractFile: (archive: string, file: string) => Buffer;
    };
    entry = (JSON.parse(extractFile(asarPath, 'package.json').toString('utf8')) as { main?: string })
      .main;
    main = join(asarPath, entry ?? '');
  } else if (existsSync(plainPkg)) {
    entry = (JSON.parse(readFileSync(plainPkg, 'utf8')) as { main?: string }).main;
    main = join(resourcesDir, 'app', entry ?? '');
  } else {
    throw new Error(
      `${APP_EXE_ENV}=${bundle} is not a launchable Electron app tree ` +
        `(expected Contents/Resources/app.asar or Contents/Resources/app/package.json).`,
    );
  }
  if (!entry) {
    throw new Error(
      `${APP_EXE_ENV}=${bundle}: the bundle's package.json declares no "main" entry, so there ` +
        'is nothing to launch.',
    );
  }
  return { main, executablePath: join(macosDir, inner), packaged: true };
}

/**
 * Resolve the app under test, PREFERRING a real electron-builder package so the
 * E2E drives the SHIPPED binary (the .exe on Windows). If RF_E2E_DEV is set, or
 * no package exists in `dist/`, fall back to the dev build (out/main/main.js) so
 * the same spec still gives local GUI coverage. Set RF_E2E_REQUIRE_PACKAGED=1 to
 * make the absence of a package a hard error (the packaged.spec.ts CI leg).
 *
 * :data:`APP_EXE_ENV` wins over BOTH of those: it names an app installed outside
 * the repo, so neither `dist/` nor the dev build is relevant, and the CI leg that
 * would use it already exports `RF_E2E_DEV=1` job-wide for `preview.spec`.
 */
export function findBuiltApp(): BuiltApp {
  const installed = process.env[APP_EXE_ENV]?.trim();
  if (installed) return resolveInstalledApp(installed);
  const requirePackaged = process.env.RF_E2E_REQUIRE_PACKAGED === '1';
  // RF_E2E_DEV forces the dev build (used to run preview.spec's data-pipeline
  // against the dev build on the Windows leg). But packaged.spec self-sets
  // RF_E2E_REQUIRE_PACKAGED in the SAME process — that ALWAYS wins, so the
  // packaged-only spec still drives the real .exe even when RF_E2E_DEV is set.
  const wantDev = !requirePackaged && process.env.RF_E2E_DEV === '1';
  if (!wantDev && existsSync(DIST_DIR)) {
    const diag: string[] = [];
    // electron-builder writes its UNPACKED app tree to a per-platform dir
    // (win-unpacked / linux-unpacked / mac[-arm64]); the installers (.exe/.zip)
    // sit beside it. parseElectronApp needs the UNPACKED dir, not an installer.
    // Try the deterministic dirs first, then fall back to findLatestBuild
    // (which itself only accepts a "<platform>-…" DIRECTORY, never an installer).
    const candidates = ['win-unpacked', 'linux-unpacked', 'mac', 'mac-arm64'];
    for (const candidate of candidates) {
      const dir = join(DIST_DIR, candidate);
      if (!existsSync(dir)) continue;
      try {
        const info = parseElectronApp(dir);
        // Only the EXECUTABLE must exist on disk. info.main is the app entry as
        // electron.launch wants it — for an asar build that is a path INSIDE
        // app.asar (e.g. resources/app.asar/out/main/main.js), which existsSync()
        // always reports false even though Electron resolves it fine; never gate
        // on it.
        if (existsSync(info.executable)) {
          return { main: info.main, executablePath: info.executable, packaged: true };
        }
        diag.push(`${candidate}: parsed but executable missing (${info.executable})`);
      } catch (err) {
        const inside = readdirSync(dir).slice(0, 20).join(',');
        diag.push(`${candidate}: ${(err as Error).message} [contains: ${inside}]`);
      }
    }
    try {
      const latest = findLatestBuild(DIST_DIR);
      const info = parseElectronApp(latest);
      if (existsSync(info.executable)) {
        return { main: info.main, executablePath: info.executable, packaged: true };
      }
      diag.push(`findLatestBuild(${latest}): executable missing (${info.executable})`);
    } catch (err) {
      diag.push(`findLatestBuild: ${(err as Error).message}`);
    }
    if (requirePackaged) {
      const listing = readdirSync(DIST_DIR).join(', ');
      throw new Error(
        `electron-builder output present under ${DIST_DIR} but no launchable package resolved ` +
          `(RF_E2E_REQUIRE_PACKAGED=1). dist contents: [${listing}]. attempts: ${diag.join(' | ')}`,
      );
    }
  }
  if (requirePackaged) {
    throw new Error(
      `no electron-builder output dir found at ${DIST_DIR} (RF_E2E_REQUIRE_PACKAGED=1). ` +
        'Run electron-builder before this packaged-only leg.',
    );
  }
  if (!existsSync(MAIN_ENTRY)) {
    throw new Error(`built main entry missing: ${MAIN_ENTRY} — run \`npm run build\` first`);
  }
  return { main: MAIN_ENTRY, packaged: false };
}

/**
 * The Python 3.12 interpreter to run the sidecar with. RF_PY (set by the test
 * runner / CI) wins; otherwise the Windows `py -3.12` launcher is resolved to a
 * concrete executable so the SAME interpreter seeds the library AND backs the
 * launched app (a single MEDIA_STUDIO_PYTHON value).
 */
export function resolvePython(): string {
  const fromEnv = process.env.RF_PY?.trim();
  if (fromEnv) return fromEnv;
  const probe = spawnSync('py', ['-3.12', '-c', 'import sys;print(sys.executable)'], {
    encoding: 'utf8',
  });
  const out = probe.stdout?.trim();
  if (probe.status === 0 && out) return out;
  // POSIX / CI fallback.
  return 'python3';
}

export interface SeededEnv {
  /** Fresh per-run data root (MEDIA_STUDIO_CONFIG_DIR). */
  dataRoot: string;
  /** Absolute path to the generated sample MP4. */
  samplePath: string;
  /** Library id assigned to the sample by `library.add`. */
  videoId: string;
  /** Python interpreter path used for the sidecar. */
  python: string;
  /** The env the launched Electron app must inherit (no undefined values). */
  appEnv: Record<string, string>;
}

/** Drop undefined values so the env satisfies Playwright's `{[k]: string}`. */
function definedEnv(extra: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(process.env)) {
    if (typeof v === 'string') out[k] = v;
  }
  return { ...out, ...extra };
}

/**
 * Generate a real 3s H.264/AAC MP4 (faststart) Chromium can decode.
 *
 * EXPORTED (it was module-private) so a spec can make a SECOND real video that is
 * deliberately NOT registered in the library — the file
 * `add-videos-dialog.spec.ts` hands to the stubbed native picker, so the add path
 * is driven with real bytes rather than a fabricated path.
 */
export function generateSample(samplePath: string): void {
  const args = [
    '-y',
    '-f',
    'lavfi',
    '-i',
    'testsrc=duration=3:size=640x360:rate=24',
    '-f',
    'lavfi',
    '-i',
    'sine=frequency=440:duration=3',
    '-c:v',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-movflags',
    '+faststart',
    '-c:a',
    'aac',
    '-shortest',
    samplePath,
  ];
  const r = spawnSync(process.env.RF_FFMPEG?.trim() || 'ffmpeg', args, { encoding: 'utf8' });
  if (r.status !== 0 || !existsSync(samplePath)) {
    throw new Error(`ffmpeg sample generation failed (status ${r.status}): ${r.stderr ?? ''}`);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// SPEECH FIXTURE — a REAL spoken-word sample, synthesised at test time.
//
// WHY this exists: until it did, NO test in the repository proved that a spoken
// word becomes text. The only media fixture was `generateSample` above
// (`testsrc` + a 440 Hz `sine`), which carries no speech at all — so
// `golden-journey.spec.ts` deliberately drives the manual-range path, and
// `sidecar/tests/e2e/real_pipeline_smoke.py` asserts an EMPTY transcript and says
// so in its own output. Transcription and captioning were therefore unproven in
// BOTH directions: no evidence they worked, and none that they did not.
//
// WHY Windows-only SAPI and not a committed audio file: the repo tracks ZERO
// audio/video binaries (verified: `git ls-tree -r --name-only origin/main` has no
// media extensions), and adding a redistributable speech clip drags in a licence
// question plus a binary in git. Windows ships a speech synthesiser in the OS
// (`System.Speech.Synthesis.SpeechSynthesizer`, .NET), so the fixture GENERATES
// its own speech offline, keeps nothing, and redistributes nothing. The cost is
// that it only runs on Windows — the consuming spec must therefore `test.skip()`
// LOUDLY elsewhere (see transcribe-journey.spec.ts) rather than pass vacuously.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The phrase the fixture speaks. Chosen for ASR-hostile-but-recoverable content:
 * the pangram gives short, high-frequency, hard-to-mishear nouns, and the second
 * sentence names the product's actual job.
 *
 * Measured (this box, `Microsoft David Desktop`): 22050 Hz mono `pcm_s16le`,
 * 6.748 s, 297,640 bytes.
 */
export const SPEECH_PHRASE =
  'The quick brown fox jumps over the lazy dog. Reframe converts landscape video to vertical.';

/**
 * The content words a transcript of :data:`SPEECH_PHRASE` must contain.
 *
 * DELIBERATELY NOT the product name. Measured with the shipped stack
 * (faster_whisper 1.2.1, model `tiny`, cpu/int8) the transcript came back as
 * "…lazy dog. **Refrain** converts landscape video to vertical." — "Reframe" was
 * misheard. An exact-sentence or product-name assertion would therefore be flaky
 * BY CONSTRUCTION, and a flaky keystone is a worse defect than the hole it closes.
 */
export const SPEECH_KEYWORDS: readonly string[] = ['fox', 'dog', 'landscape', 'vertical'];

/**
 * How many of :data:`SPEECH_KEYWORDS` a real transcript must carry.
 *
 * DO NOT "tighten" this to `SPEECH_KEYWORDS.length`. The synthesised voice is
 * whatever the machine has installed, and `tiny` is the cheapest whisper model —
 * so which individual words survive is machine-dependent. (Voice-count
 * correction: this comment used to say "10 SAPI voices". MEASURED through the
 * SAME `System.Speech.Synthesis` enumeration the fixture uses, this box exposes
 * **3** — all enabled, all `en-*`. The 10 counts the OneCore voices too:
 * `HKLM:\SOFTWARE\Microsoft\Speech\Voices\Tokens` has 3 tokens and
 * `…\Speech_OneCore\Voices\Tokens` has 7, and `System.Speech` enumerates only the
 * former, so 3 is the fixture's real selection pool. A GitHub windows-latest
 * image ships its own set — UNVERIFIED which; the settling experiment is the
 * `VOICE=` line this fixture already prints on every CI run.)
 *
 * SCOPE CORRECTION. An earlier version of this comment claimed the both-states
 * proof for the THRESHOLD: "the same assertion scores 0 hits on the speechless
 * `sine` sample (measured)". That was REFUTED and is wrong about which assertion
 * the sine run exercises: on speechless audio the spec dies EARLIER, at the
 * zero-segments arm (`transcribe-journey.spec.ts`, `.not.toHaveCount(0)`), so the
 * keyword arm is never evaluated there. What is actually measured:
 *   * the ZERO-SEGMENTS arm is both-states verified (sine red / speech green);
 *   * the threshold's own failing direction is covered by
 *     `speechKeywords.test.ts` — a 1-hit transcript is BELOW this floor and a
 *     2-hit one is at it, so the arm demonstrably fails closed;
 *   * the margin is wide: MEASURED by synthesising SPEECH_PHRASE with EACH of the
 *     3 enabled `en-*` voices, muxing each the way `generateSpeechSample` does and
 *     transcribing with `tiny`/cpu/int8 — David 4/4, Hazel 4/4, Zira 4/4, the only
 *     difference being the product name ("Refrain" / "Refrain" / "Reframed"),
 *     while the CONTROL (the repo's own 3 s `sine`) transcribed to `''` = 0 hits.
 * So 2 tolerates one mangled word without ever tolerating silence.
 */
export const SPEECH_KEYWORD_MIN_HITS = 2;

/** Which of :data:`SPEECH_KEYWORDS` appear in `text` (case-insensitive). */
export function matchedSpeechKeywords(text: string): string[] {
  const low = text.toLowerCase();
  return SPEECH_KEYWORDS.filter((k) => low.includes(k));
}

/**
 * The SAPI synthesiser, as a script rather than an inline `-Command`.
 *
 * Written to the per-run data root at test time (never committed) so it carries
 * no `.gitattributes` end-of-line question and no shell-quoting hazard: the
 * phrase and the output path arrive as bound `param()` values through argv, not
 * spliced into a command line.
 *
 * Voice selection is by CULTURE (`en*`), not by name, so it works on any Windows
 * image; it FAILS LOUD when no enabled English voice exists rather than silently
 * producing a 0-byte file that would read as "transcription is broken".
 *
 * MEASURED — the guard's exit code is 1, NOT the literal 3 in the script. Under
 * `$ErrorActionPreference = 'Stop'` the `Write-Error` is TERMINATING, so it
 * unwinds through `finally` and PowerShell exits 1 before `exit 3` is reached.
 * The `exit 3` is therefore belt-and-braces, not the observed code, and this
 * comment used to claim otherwise. Both states measured through the SAME
 * `spawnSync` shape the caller below uses:
 *   no en-* voice -> status=1, no file, stderr "no ENABLED … SAPI voice …"
 *   en-* voice    -> status=0, file present, stdout "VOICE=…\nBYTES=…"
 * which is why the caller's guard is `status !== 0 || !existsSync(...)`: the OR
 * makes it fail closed regardless of which code PowerShell picks.
 */
const SAPI_SCRIPT = [
  '[CmdletBinding()]',
  'param([Parameter(Mandatory=$true)][string]$Text,[Parameter(Mandatory=$true)][string]$Out)',
  "$ErrorActionPreference = 'Stop'",
  'Add-Type -AssemblyName System.Speech',
  '$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer',
  'try {',
  "  $voices = @($synth.GetInstalledVoices() | Where-Object { $_.Enabled -and $_.VoiceInfo.Culture.Name -like 'en*' })",
  '  if ($voices.Count -eq 0) { Write-Error "no ENABLED en-* SAPI voice on this machine"; exit 3 }',
  '  $pick = ($voices | Sort-Object { $_.VoiceInfo.Name } | Select-Object -First 1).VoiceInfo.Name',
  '  $synth.SelectVoice($pick)',
  '  $synth.Rate = 0',
  '  $synth.SetOutputToWaveFile($Out)',
  '  $synth.Speak($Text)',
  '  $synth.SetOutputToNull()',
  '  Write-Output "VOICE=$pick"',
  '} finally { $synth.Dispose() }',
  'if (-not (Test-Path -LiteralPath $Out)) { Write-Error "SAPI produced no file at $Out"; exit 4 }',
  'Write-Output "BYTES=$((Get-Item -LiteralPath $Out).Length)"',
  '',
].join('\n');

/** What the speech fixture produced — surfaced so a run self-documents. */
export interface SpeechFixture {
  /** Absolute path to the synthesised WAV (kept for diagnostics). */
  wavPath: string;
  /** The SAPI voice actually used (machine-dependent; logged, never asserted). */
  voice: string;
  /** Real duration of the synthesised speech, from ffprobe. */
  speechDurationSec: number;
}

/** Duration in seconds of any media file, read with the spec's own ffprobe. */
export function probeDurationSec(mediaPath: string): number {
  const r = spawnSync(
    resolveFfprobe(),
    ['-v', 'error', '-show_entries', 'format=duration', '-of', 'default=nw=1:nk=1', mediaPath],
    { encoding: 'utf8' },
  );
  if (r.status !== 0) {
    throw new Error(`ffprobe duration failed (status ${r.status}) on ${mediaPath}: ${r.stderr ?? ''}`);
  }
  const seconds = Number((r.stdout ?? '').trim());
  if (!Number.isFinite(seconds) || seconds <= 0) {
    throw new Error(`ffprobe reported a non-positive duration (${r.stdout?.trim()}) for ${mediaPath}`);
  }
  return seconds;
}

/**
 * Synthesise :data:`SPEECH_PHRASE` to `wavPath` via Windows SAPI. Windows-only.
 *
 * `scriptDir` is where the throwaway .ps1 lands (the per-run data root).
 */
export function synthesizeSpeechWav(wavPath: string, scriptDir: string, text = SPEECH_PHRASE): string {
  if (process.platform !== 'win32') {
    throw new Error('synthesizeSpeechWav requires Windows SAPI (System.Speech); guard with test.skip');
  }
  const scriptPath = join(scriptDir, 'sapi-speech.ps1');
  writeFileSync(scriptPath, SAPI_SCRIPT, 'utf8');
  const r = spawnSync(
    'powershell.exe',
    ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', scriptPath, '-Text', text, '-Out', wavPath],
    { encoding: 'utf8' },
  );
  if (r.status !== 0 || !existsSync(wavPath)) {
    throw new Error(
      `SAPI speech synthesis failed (status ${r.status}) -> ${wavPath}\n` +
        `stdout: ${r.stdout ?? ''}\nstderr: ${r.stderr ?? ''}`,
    );
  }
  const voice = /VOICE=(.+)/.exec(r.stdout ?? '')?.[1]?.trim() ?? '';
  if (!voice) throw new Error(`SAPI script did not report a voice; stdout: ${r.stdout ?? ''}`);
  return voice;
}

/**
 * Generate a real H.264/AAC MP4 that CARRIES SPEECH: the same `testsrc` video the
 * silent fixture uses, muxed with a SAPI-synthesised speech track.
 *
 * The video is generated at `ceil(speech) + 2` s and the mux uses `-shortest`, so
 * the output length equals the SPEECH length and the whole phrase is carried. The
 * 3 s silent sample would truncate ~7 s of speech, which is precisely why this
 * does not just reuse it.
 */
export function generateSpeechSample(samplePath: string, workDir: string): SpeechFixture {
  const wavPath = join(workDir, 'speech.wav');
  const voice = synthesizeSpeechWav(wavPath, workDir);
  const speechDurationSec = probeDurationSec(wavPath);
  const videoSec = Math.ceil(speechDurationSec) + 2;
  const args = [
    '-y',
    '-f',
    'lavfi',
    '-i',
    `testsrc=duration=${videoSec}:size=640x360:rate=24`,
    '-i',
    wavPath,
    '-c:v',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-movflags',
    '+faststart',
    '-c:a',
    'aac',
    '-shortest',
    samplePath,
  ];
  const r = spawnSync(process.env.RF_FFMPEG?.trim() || 'ffmpeg', args, { encoding: 'utf8' });
  if (r.status !== 0 || !existsSync(samplePath)) {
    throw new Error(`ffmpeg speech-sample mux failed (status ${r.status}): ${r.stderr ?? ''}`);
  }
  return { wavPath, voice, speechDurationSec };
}

/** Run one JSON-RPC request against a one-shot sidecar process; return result. */
function sidecarCall(python: string, dataRoot: string, method: string, params: unknown): unknown {
  const req = `${JSON.stringify({ jsonrpc: '2.0', id: 1, method, params })}\n`;
  const r = spawnSync(python, ['-m', 'media_studio'], {
    cwd: SIDECAR_DIR,
    input: req,
    encoding: 'utf8',
    env: { ...process.env, MEDIA_STUDIO_CONFIG_DIR: dataRoot },
  });
  const lines = (r.stdout ?? '').split('\n').filter((l) => l.trim().startsWith('{'));
  for (const line of lines) {
    const msg = JSON.parse(line) as { id?: number; result?: unknown; error?: unknown };
    if (msg.id === 1) {
      if (msg.error) throw new Error(`sidecar ${method} error: ${JSON.stringify(msg.error)}`);
      return msg.result;
    }
  }
  throw new Error(`sidecar ${method}: no response (status ${r.status}) stderr=${r.stderr ?? ''}`);
}

/**
 * Writes the seeded sample media into `samplePath`. `workDir` is the per-run data
 * root, for any intermediate the generator needs (e.g. the speech WAV).
 */
export type MediaGenerator = (samplePath: string, workDir: string) => void;

/**
 * Build a fresh data root, generate a real sample MP4, register it through the
 * real sidecar `library.add`, and return everything the launched app needs.
 *
 * `generateMedia` defaults to the silent `testsrc`+`sine` sample, so every
 * existing caller is byte-for-byte unchanged; the transcribe journey passes
 * :func:`generateSpeechSample` to get a SPEECH-bearing sample through the exact
 * same seeding path (same `library.add`, same thumbnail, same env).
 *
 * The default is `generateSample`, which takes ONE parameter and therefore ignores
 * the `workDir` second argument — that is WHY the zero-argument callers are
 * unchanged rather than merely "probably fine". They are enumerated here so the
 * count is checkable instead of asserted (a review of this branch put it at three
 * by grepping only `e2e/*.spec.ts`; it is FOUR — the visual suite's helper is easy
 * to miss because it lives under `e2e/visual/`, outside playwright.config.ts):
 *   * `preview.spec.ts`               (executed on this branch: 9/9 green)
 *   * `golden-journey.spec.ts`        (NOT executed here — UNVERIFIED)
 *   * `packaged.spec.ts`              (NOT executed here — UNVERIFIED)
 *   * `visual/_visualSetup.ts` `launchSeededApp()`, i.e. every visual + a11y spec
 *                                     (NOT executed here — UNVERIFIED)
 * The settling experiment for the three unexecuted ones is a full
 * `npm run test:e2e` + `npm run test:e2e:visual`; the argument that they cannot
 * have changed is the arity one above, not the test evidence.
 */
export function seedEnvironment(generateMedia: MediaGenerator = generateSample): SeededEnv {
  const python = resolvePython();
  // realpathSync.NATIVE expands the tmp path's 8.3 SHORT name to its LONG form.
  // os.tmpdir() on Windows returns the SHORT name (C:\Users\PREKZU~1\...), which
  // becomes main's DATA_ROOT — but the sidecar canonicalises its thumbnail path to
  // the LONG form (C:\Users\Prekzursil\...). The mstream `thumb:` containment guard
  // (startsWith) then rejects the poster (short root vs long path) → a 404. Plain
  // realpathSync does NOT expand short names (verified); .native does. A real
  // install's %APPDATA% root has no short/long split; canonicalising here matches it.
  const dataRoot = realpathSync.native(mkdtempSync(join(tmpdir(), 'reframe-e2e-data-')));
  const samplePath = join(dataRoot, 'sample.mp4');
  generateMedia(samplePath, dataRoot);

  const added = sidecarCall(python, dataRoot, 'library.add', { path: samplePath }) as {
    video: { id: string };
  };
  const videoId = added.video.id;

  // Generate the source poster frame so the Library card's `thumb:` request resolves
  // instead of 404-ing in the sandboxed renderer. `library.thumbnail` is a SYNC RPC
  // (verified: it runs ffmpeg and writes data_dir/thumbnails/<id>.jpg before
  // returning), so the one-shot sidecarCall completes the write. The app does this
  // on demand (useVideoThumbnail); an out-of-band seed must do it too. Not swallowed:
  // a thumbnail failure is a real setup problem worth surfacing, not hiding.
  sidecarCall(python, dataRoot, 'library.thumbnail', { id: videoId });

  const appEnv = definedEnv({
    MEDIA_STUDIO_PYTHON: python,
    MEDIA_STUDIO_SIDECAR_DIR: SIDECAR_DIR,
    MEDIA_STUDIO_CONFIG_DIR: dataRoot,
  });

  return { dataRoot, samplePath, videoId, python, appEnv };
}

/**
 * Provision assets (a LONG job) by driving a live sidecar until the ensure job
 * reports `job.done`. Unlike `sidecarCall` (one-shot spawnSync, which would kill
 * the download when the RPC returns), this keeps the sidecar alive and streams its
 * stdout until the `assets.ensure` job completes. Used to seed the core reframe
 * model (YuNet) into the data root — the SAME step a real first-run performs —
 * so the default `reframeEngine:"auto"` (claudeshorts) path can actually reframe.
 */
export function provisionAssets(python: string, dataRoot: string, names: string[]): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    const proc = spawn(python, ['-m', 'media_studio'], {
      cwd: SIDECAR_DIR,
      env: { ...process.env, MEDIA_STUDIO_CONFIG_DIR: dataRoot },
    });
    let buf = '';
    let jobId = '';
    // Capture the sidecar's stderr so a SILENT provisioning failure (e.g. a missing
    // download dep -> assets.ensure gracefully SKIPS the item but still reports
    // job.done) is surfaced in the rejection instead of only manifesting later as a
    // mysterious "model not provisioned" at reframe time.
    let stderr = '';
    proc.stderr.setEncoding('utf8');
    proc.stderr.on('data', (chunk: string) => {
      stderr += chunk;
    });
    const timer = setTimeout(() => {
      proc.kill();
      reject(new Error(`provisionAssets(${names.join(',')}) timed out\n${stderr}`));
    }, 300_000);
    const done = (err?: Error): void => {
      clearTimeout(timer);
      proc.kill();
      if (err) reject(err);
      else resolve();
    };
    proc.stdout.setEncoding('utf8');
    proc.stdout.on('data', (chunk: string) => {
      buf += chunk;
      let nl: number;
      while ((nl = buf.indexOf('\n')) >= 0) {
        const line = buf.slice(0, nl).trim();
        buf = buf.slice(nl + 1);
        if (!line.startsWith('{')) continue;
        let msg: {
          id?: number;
          method?: string;
          result?: { jobId?: string };
          params?: { jobId?: string; result?: { installed?: string[] } };
        };
        try {
          msg = JSON.parse(line);
        } catch {
          continue;
        }
        if (msg.id === 1 && msg.result?.jobId) jobId = msg.result.jobId;
        if (msg.params?.jobId === jobId && msg.method === 'job.done') {
          // VERIFY the requested assets actually installed. assets.ensure emits
          // job.done even when it GRACEFULLY SKIPS a failed item (WU C1), so a silent
          // download failure would otherwise pass as success here and only surface
          // as "model not provisioned" deep in the reframe stage.
          const installed = msg.params.result?.installed ?? [];
          const missing = names.filter((n) => !installed.includes(n));
          if (missing.length > 0) {
            done(
              new Error(
                `provisionAssets: ${missing.join(', ')} did not install ` +
                  `(installed=${JSON.stringify(installed)}); sidecar stderr:\n${stderr}`,
              ),
            );
          } else {
            done();
          }
        }
        if (msg.params?.jobId === jobId && msg.method === 'job.error') {
          done(new Error(`provisionAssets job.error: ${JSON.stringify(msg.params)}\n${stderr}`));
        }
      }
    });
    proc.on('error', reject);
    proc.stdin.write(
      `${JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'assets.ensure', params: { names } })}\n`,
    );
  });
}

/**
 * Write settings into the per-run data root through the REAL `settings.set` RPC
 * (the same one the Settings UI calls), returning the merged result.
 *
 * Used by the transcribe journey to PIN the ASR target before the app launches.
 * Not a mock: `SettingsStore.set` merges + persists to `<dataRoot>/settings.json`,
 * which is exactly where `_transcribe_and_persist` reads it from at job time.
 *
 * CONTRACT-NOTE: `settings.set`'s PARAMS OBJECT *is* the value map — the handler
 * is `self.settings.set(dict(params))` (handlers/library_ops.py:382), with no
 * `{values: …}` envelope. Wrapping it would silently persist a `values` key and
 * leave `transcribeModel` unset, which is exactly the kind of no-op setup that
 * makes a test measure nothing.
 */
export function applySettings(
  python: string,
  dataRoot: string,
  values: Record<string, unknown>,
): Record<string, unknown> {
  return sidecarCall(python, dataRoot, 'settings.set', values) as Record<string, unknown>;
}

/** One library row as `library.list` returns it (only the fields specs assert on). */
export interface LibraryRow {
  id: string;
  /** Absolute source path, as the sidecar canonicalised it (`Path.resolve`). */
  path: string;
  title: string;
}

/**
 * Read the library straight out of the data root through the real `library.list`.
 *
 * This is a SECOND, mechanically-independent signal for any spec that asserts a
 * GUI add: the DOM says a card appeared, and this says the sidecar PERSISTED a row
 * for that file. A renderer that optimistically painted a card without the RPC
 * landing would satisfy the first and fail this one.
 */
export function listLibraryVideos(python: string, dataRoot: string): LibraryRow[] {
  const result = sidecarCall(python, dataRoot, 'library.list', {}) as { videos?: LibraryRow[] };
  return result.videos ?? [];
}

/** Direct `media.playable` probe (used to label the preview path honestly). */
export function probePlayable(
  python: string,
  dataRoot: string,
  videoId: string,
): { playable: boolean; proxyPath?: string } {
  return sidecarCall(python, dataRoot, 'media.playable', { videoId }) as {
    playable: boolean;
    proxyPath?: string;
  };
}

/**
 * The `resources/bin/ffmpeg` that a PACKAGED artifact actually ships and runs.
 *
 * electron-builder maps `build/ffmpeg/win -> resources/bin` (electron-builder.yml
 * extraResources), and the packaged main process points the sidecar at exactly
 * this path via MEDIA_STUDIO_FFMPEG (`buildSidecarEnv`; see app/main/
 * sidecar.env.test.ts §A3 — `<resourcesPath>/bin/ffmpeg.exe`). So this is THE
 * binary a shipped export runs through, and the only one whose capabilities a
 * packaged smoke may trust. Verified against a real install: an executable at
 * `D:/Program Files/Reframe/Reframe.exe` yields
 * `D:/Program Files/Reframe/resources/bin/ffmpeg.exe`.
 *
 * SCOPE CORRECTION (refuted 2026-08-11). This was `dirname(exe)/resources/bin` +
 * a `process.platform === 'win32'` suffix, and both halves were wrong for the
 * macOS input `APP_EXE_ENV` documents as supported:
 *   * a `.app`'s executable is `<bundle>/Contents/MacOS/<name>`, so the flat
 *     `dirname` produced `<bundle>/Contents/MacOS/resources/bin/ffmpeg` — but
 *     electron-builder puts extraResources at `<bundle>/Contents/Resources/`.
 *     MEASURED red before this fix. `installed-app.spec.ts` asserts `existsSync`
 *     on the result with the message "NSIS is NOT laying resources out
 *     identically", i.e. a Mac maintainer following the spec's own printed
 *     instructions got a false diagnosis naming an installer that is not involved.
 *   * `process.platform` is the HOST, not the tree under test. Both are now
 *     derived from the TARGET PATH — a property of the input, which is what lets
 *     `findBuiltApp.test.ts` assert every layout identically on every runner
 *     (the same reasoning its win32-on-Linux arm already relies on).
 * These are string tests on how the path is SPELLED, not filesystem probes, so
 * they answer the same on NTFS, APFS and ext4.
 */
export function bundledFfmpegPath(executablePath: string): string {
  const dir = dirname(executablePath);
  const binary = `ffmpeg${executablePath.toLowerCase().endsWith('.exe') ? '.exe' : ''}`;
  // A macOS bundle: `<bundle>/Contents/MacOS/<name>` -> `<bundle>/Contents/Resources`.
  if (basename(dir).toLowerCase() === 'macos' && basename(dirname(dir)).toLowerCase() === 'contents') {
    return join(dirname(dir), 'Resources', 'bin', binary);
  }
  return join(dir, 'resources', 'bin', binary);
}

/**
 * Resolve `ffprobe` for the spec's OWN independent probe of a produced clip.
 * Mirrors generateSample's ffmpeg resolution so the golden journey carries no new
 * precondition beyond the ffmpeg/ffprobe toolchain it already needs: RF_FFPROBE
 * wins; else derive the sibling of RF_FFMPEG (…/ffmpeg[.exe] → …/ffprobe[.exe]);
 * else the packaged MEDIA_STUDIO_FFPROBE; else `ffprobe` on PATH.
 */
export function resolveFfprobe(): string {
  const explicit = process.env.RF_FFPROBE?.trim();
  if (explicit) return explicit;
  const ffmpeg = process.env.RF_FFMPEG?.trim();
  if (ffmpeg) {
    const swapped = ffmpeg.replace(/ffmpeg(\.exe)?$/i, (_m, ext: string | undefined) => `ffprobe${ext ?? ''}`);
    if (swapped !== ffmpeg) return swapped;
  }
  const bundled = process.env.MEDIA_STUDIO_FFPROBE?.trim();
  if (bundled) return bundled;
  return 'ffprobe';
}

/** ffprobe facts read straight off a produced FILE (not the app's shorts.list metadata). */
export interface ProbedVideo {
  width: number;
  height: number;
  vcodec: string;
  pixFmt: string;
  /** Container duration in seconds (real playable length, NOT a metadata field). */
  durationSec: number;
  sizeBytes: number;
  /** null when the produced file carries no audio stream. */
  acodec: string | null;
}

/**
 * Independently `ffprobe` a produced .mp4 — the EXTERNAL done-signal. Deliberately
 * does NOT trust the app's `shorts.list` (which reports durationSec from a sidecar
 * .json and carries no codec), so a truncated / wrong-geometry / non-h264 file
 * cannot masquerade as "a real playable vertical short". Reads geometry + codec +
 * pixel format off the video stream and duration/size off the container.
 */
export function probeVideo(producedPath: string): ProbedVideo {
  const ffprobe = resolveFfprobe();
  const args = [
    '-v', 'error',
    '-show_entries', 'stream=codec_type,codec_name,width,height,pix_fmt',
    '-show_entries', 'format=duration,size',
    '-of', 'json',
    producedPath,
  ];
  const r = spawnSync(ffprobe, args, { encoding: 'utf8' });
  if (r.status !== 0) {
    throw new Error(`ffprobe failed (status ${r.status}) on ${producedPath}: ${r.stderr ?? ''}`);
  }
  const parsed = JSON.parse(r.stdout) as {
    streams?: Array<{
      codec_type?: string;
      codec_name?: string;
      width?: number;
      height?: number;
      pix_fmt?: string;
    }>;
    format?: { duration?: string; size?: string };
  };
  const streams = parsed.streams ?? [];
  const v = streams.find((s) => s.codec_type === 'video');
  const a = streams.find((s) => s.codec_type === 'audio');
  if (!v) throw new Error(`ffprobe found no video stream in ${producedPath}`);
  return {
    width: v.width ?? 0,
    height: v.height ?? 0,
    vcodec: v.codec_name ?? '',
    pixFmt: v.pix_fmt ?? '',
    durationSec: Number(parsed.format?.duration ?? 0),
    sizeBytes: Number(parsed.format?.size ?? 0),
    acodec: a?.codec_name ?? null,
  };
}
