// e2e/fixtures.ts — deterministic test-environment setup for the Reframe GUI E2E.
//
// Builds a throwaway, per-run data root and seeds it with ONE real sample video
// so the launched Electron app shows a library entry to open + preview. Nothing
// here mocks the app: the sample is a genuine H.264/AAC MP4 generated by ffmpeg,
// and it is registered through the SAME `library.add` JSON-RPC the running app
// would call (driven against the real Python sidecar), so `media.playable`
// resolves it to the source path and the mstream protocol streams real bytes.
//
// Why seed out-of-band instead of clicking "Add videos": the add path goes
// through a NATIVE OS file dialog (dialog.openVideos), which Playwright cannot
// drive headlessly. Seeding the data root the sidecar reads is equivalent — the
// app lists + opens + plays the exact same library record either way.

import { spawn, spawnSync } from 'node:child_process';
import { mkdtempSync, existsSync, readdirSync, realpathSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { findLatestBuild, parseElectronApp } from 'electron-playwright-helpers';

// ESM (the app package is "type": "module"): derive __dirname from import.meta.
const HERE = dirname(fileURLToPath(import.meta.url));

/** Absolute path to the repo root (two levels up from app/e2e). */
export const REPO_ROOT = resolve(HERE, '..', '..');
/** The Python sidecar package dir (cwd for `-m media_studio`). */
export const SIDECAR_DIR = join(REPO_ROOT, 'sidecar');
/** The built main-process entry the launched Electron app boots (DEV build). */
export const MAIN_ENTRY = join(REPO_ROOT, 'app', 'out', 'main', 'main.js');
/** electron-builder packaged-artifact output dir (electron-builder.yml). */
export const DIST_DIR = join(REPO_ROOT, 'dist');

/**
 * What the launched app boots: the args + (for a real package) the executable
 * path, plus whether we are pointing at a PACKAGED artifact or the dev build.
 */
export interface BuiltApp {
  /** Launch args ([appInfo.main] for a package, [MAIN_ENTRY] for dev). */
  main: string;
  /** electron-builder executable path; undefined => use the dev electron bin. */
  executablePath?: string;
  /** True when resolved to a real electron-builder package (the shipped .exe). */
  packaged: boolean;
}

/**
 * Resolve the app under test, PREFERRING a real electron-builder package so the
 * E2E drives the SHIPPED binary (the .exe on Windows). If RF_E2E_DEV is set, or
 * no package exists in `dist/`, fall back to the dev build (out/main/main.js) so
 * the same spec still gives local GUI coverage. Set RF_E2E_REQUIRE_PACKAGED=1 to
 * make the absence of a package a hard error (the packaged.spec.ts CI leg).
 */
export function findBuiltApp(): BuiltApp {
  const requirePackaged = process.env.RF_E2E_REQUIRE_PACKAGED === '1';
  // RF_E2E_DEV forces the dev build (used to run preview.spec's data-pipeline
  // against the dev build on the Windows leg). But packaged.spec self-sets
  // RF_E2E_REQUIRE_PACKAGED in the SAME process — that ALWAYS wins, so the
  // packaged-only spec still drives the real .exe even when RF_E2E_DEV is set.
  const wantDev = !requirePackaged && process.env.RF_E2E_DEV === '1';
  if (!wantDev && existsSync(DIST_DIR)) {
    const diag: string[] = [];
    // electron-builder writes its UNPACKED app tree to a per-platform dir
    // (win-unpacked / linux-unpacked / mac[-arm64]); the installers (.exe/.zip)
    // sit beside it. parseElectronApp needs the UNPACKED dir, not an installer.
    // Try the deterministic dirs first, then fall back to findLatestBuild
    // (which itself only accepts a "<platform>-…" DIRECTORY, never an installer).
    const candidates = ['win-unpacked', 'linux-unpacked', 'mac', 'mac-arm64'];
    for (const candidate of candidates) {
      const dir = join(DIST_DIR, candidate);
      if (!existsSync(dir)) continue;
      try {
        const info = parseElectronApp(dir);
        // Only the EXECUTABLE must exist on disk. info.main is the app entry as
        // electron.launch wants it — for an asar build that is a path INSIDE
        // app.asar (e.g. resources/app.asar/out/main/main.js), which existsSync()
        // always reports false even though Electron resolves it fine; never gate
        // on it.
        if (existsSync(info.executable)) {
          return { main: info.main, executablePath: info.executable, packaged: true };
        }
        diag.push(`${candidate}: parsed but executable missing (${info.executable})`);
      } catch (err) {
        const inside = readdirSync(dir).slice(0, 20).join(',');
        diag.push(`${candidate}: ${(err as Error).message} [contains: ${inside}]`);
      }
    }
    try {
      const latest = findLatestBuild(DIST_DIR);
      const info = parseElectronApp(latest);
      if (existsSync(info.executable)) {
        return { main: info.main, executablePath: info.executable, packaged: true };
      }
      diag.push(`findLatestBuild(${latest}): executable missing (${info.executable})`);
    } catch (err) {
      diag.push(`findLatestBuild: ${(err as Error).message}`);
    }
    if (requirePackaged) {
      const listing = readdirSync(DIST_DIR).join(', ');
      throw new Error(
        `electron-builder output present under ${DIST_DIR} but no launchable package resolved ` +
          `(RF_E2E_REQUIRE_PACKAGED=1). dist contents: [${listing}]. attempts: ${diag.join(' | ')}`,
      );
    }
  }
  if (requirePackaged) {
    throw new Error(
      `no electron-builder output dir found at ${DIST_DIR} (RF_E2E_REQUIRE_PACKAGED=1). ` +
        'Run electron-builder before this packaged-only leg.',
    );
  }
  if (!existsSync(MAIN_ENTRY)) {
    throw new Error(`built main entry missing: ${MAIN_ENTRY} — run \`npm run build\` first`);
  }
  return { main: MAIN_ENTRY, packaged: false };
}

/**
 * The Python 3.12 interpreter to run the sidecar with. RF_PY (set by the test
 * runner / CI) wins; otherwise the Windows `py -3.12` launcher is resolved to a
 * concrete executable so the SAME interpreter seeds the library AND backs the
 * launched app (a single MEDIA_STUDIO_PYTHON value).
 */
export function resolvePython(): string {
  const fromEnv = process.env.RF_PY?.trim();
  if (fromEnv) return fromEnv;
  const probe = spawnSync('py', ['-3.12', '-c', 'import sys;print(sys.executable)'], {
    encoding: 'utf8',
  });
  const out = probe.stdout?.trim();
  if (probe.status === 0 && out) return out;
  // POSIX / CI fallback.
  return 'python3';
}

export interface SeededEnv {
  /** Fresh per-run data root (MEDIA_STUDIO_CONFIG_DIR). */
  dataRoot: string;
  /** Absolute path to the generated sample MP4. */
  samplePath: string;
  /** Library id assigned to the sample by `library.add`. */
  videoId: string;
  /** Python interpreter path used for the sidecar. */
  python: string;
  /** The env the launched Electron app must inherit (no undefined values). */
  appEnv: Record<string, string>;
}

/** Drop undefined values so the env satisfies Playwright's `{[k]: string}`. */
function definedEnv(extra: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(process.env)) {
    if (typeof v === 'string') out[k] = v;
  }
  return { ...out, ...extra };
}

/** Generate a real 3s H.264/AAC MP4 (faststart) Chromium can decode. */
function generateSample(samplePath: string): void {
  const args = [
    '-y',
    '-f',
    'lavfi',
    '-i',
    'testsrc=duration=3:size=640x360:rate=24',
    '-f',
    'lavfi',
    '-i',
    'sine=frequency=440:duration=3',
    '-c:v',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-movflags',
    '+faststart',
    '-c:a',
    'aac',
    '-shortest',
    samplePath,
  ];
  const r = spawnSync(process.env.RF_FFMPEG?.trim() || 'ffmpeg', args, { encoding: 'utf8' });
  if (r.status !== 0 || !existsSync(samplePath)) {
    throw new Error(`ffmpeg sample generation failed (status ${r.status}): ${r.stderr ?? ''}`);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// SPEECH FIXTURE — a REAL spoken-word sample, synthesised at test time.
//
// WHY this exists: until it did, NO test in the repository proved that a spoken
// word becomes text. The only media fixture was `generateSample` above
// (`testsrc` + a 440 Hz `sine`), which carries no speech at all — so
// `golden-journey.spec.ts` deliberately drives the manual-range path, and
// `sidecar/tests/e2e/real_pipeline_smoke.py` asserts an EMPTY transcript and says
// so in its own output. Transcription and captioning were therefore unproven in
// BOTH directions: no evidence they worked, and none that they did not.
//
// WHY Windows-only SAPI and not a committed audio file: the repo tracks ZERO
// audio/video binaries (verified: `git ls-tree -r --name-only origin/main` has no
// media extensions), and adding a redistributable speech clip drags in a licence
// question plus a binary in git. Windows ships a speech synthesiser in the OS
// (`System.Speech.Synthesis.SpeechSynthesizer`, .NET), so the fixture GENERATES
// its own speech offline, keeps nothing, and redistributes nothing. The cost is
// that it only runs on Windows — the consuming spec must therefore `test.skip()`
// LOUDLY elsewhere (see transcribe-journey.spec.ts) rather than pass vacuously.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The phrase the fixture speaks. Chosen for ASR-hostile-but-recoverable content:
 * the pangram gives short, high-frequency, hard-to-mishear nouns, and the second
 * sentence names the product's actual job.
 *
 * Measured (this box, `Microsoft David Desktop`): 22050 Hz mono `pcm_s16le`,
 * 6.748 s, 297,640 bytes.
 */
export const SPEECH_PHRASE =
  'The quick brown fox jumps over the lazy dog. Reframe converts landscape video to vertical.';

/**
 * The content words a transcript of :data:`SPEECH_PHRASE` must contain.
 *
 * DELIBERATELY NOT the product name. Measured with the shipped stack
 * (faster_whisper 1.2.1, model `tiny`, cpu/int8) the transcript came back as
 * "…lazy dog. **Refrain** converts landscape video to vertical." — "Reframe" was
 * misheard. An exact-sentence or product-name assertion would therefore be flaky
 * BY CONSTRUCTION, and a flaky keystone is a worse defect than the hole it closes.
 */
export const SPEECH_KEYWORDS: readonly string[] = ['fox', 'dog', 'landscape', 'vertical'];

/**
 * How many of :data:`SPEECH_KEYWORDS` a real transcript must carry.
 *
 * DO NOT "tighten" this to `SPEECH_KEYWORDS.length`. The synthesised voice is
 * whatever the machine has installed (this box has 10 SAPI voices; a GitHub
 * windows-latest image ships a different set), and `tiny` is the cheapest whisper
 * model — so which individual words survive is machine-dependent. What is NOT
 * machine-dependent is the difference between speech and no speech: the same
 * assertion scores 0 hits on the speechless `sine` sample (measured), so a
 * threshold of 2 still fails closed on a broken transcription while tolerating one
 * mangled word. 4/4 was observed locally; 2 is the floor we are willing to defend.
 */
export const SPEECH_KEYWORD_MIN_HITS = 2;

/** Which of :data:`SPEECH_KEYWORDS` appear in `text` (case-insensitive). */
export function matchedSpeechKeywords(text: string): string[] {
  const low = text.toLowerCase();
  return SPEECH_KEYWORDS.filter((k) => low.includes(k));
}

/**
 * The SAPI synthesiser, as a script rather than an inline `-Command`.
 *
 * Written to the per-run data root at test time (never committed) so it carries
 * no `.gitattributes` end-of-line question and no shell-quoting hazard: the
 * phrase and the output path arrive as bound `param()` values through argv, not
 * spliced into a command line.
 *
 * Voice selection is by CULTURE (`en*`), not by name, so it works on any Windows
 * image; it FAILS LOUD (exit 3) when no enabled English voice exists rather than
 * silently producing a 0-byte file that would read as "transcription is broken".
 */
const SAPI_SCRIPT = [
  '[CmdletBinding()]',
  'param([Parameter(Mandatory=$true)][string]$Text,[Parameter(Mandatory=$true)][string]$Out)',
  "$ErrorActionPreference = 'Stop'",
  'Add-Type -AssemblyName System.Speech',
  '$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer',
  'try {',
  "  $voices = @($synth.GetInstalledVoices() | Where-Object { $_.Enabled -and $_.VoiceInfo.Culture.Name -like 'en*' })",
  '  if ($voices.Count -eq 0) { Write-Error "no ENABLED en-* SAPI voice on this machine"; exit 3 }',
  '  $pick = ($voices | Sort-Object { $_.VoiceInfo.Name } | Select-Object -First 1).VoiceInfo.Name',
  '  $synth.SelectVoice($pick)',
  '  $synth.Rate = 0',
  '  $synth.SetOutputToWaveFile($Out)',
  '  $synth.Speak($Text)',
  '  $synth.SetOutputToNull()',
  '  Write-Output "VOICE=$pick"',
  '} finally { $synth.Dispose() }',
  'if (-not (Test-Path -LiteralPath $Out)) { Write-Error "SAPI produced no file at $Out"; exit 4 }',
  'Write-Output "BYTES=$((Get-Item -LiteralPath $Out).Length)"',
  '',
].join('\n');

/** What the speech fixture produced — surfaced so a run self-documents. */
export interface SpeechFixture {
  /** Absolute path to the synthesised WAV (kept for diagnostics). */
  wavPath: string;
  /** The SAPI voice actually used (machine-dependent; logged, never asserted). */
  voice: string;
  /** Real duration of the synthesised speech, from ffprobe. */
  speechDurationSec: number;
}

/** Duration in seconds of any media file, read with the spec's own ffprobe. */
export function probeDurationSec(mediaPath: string): number {
  const r = spawnSync(
    resolveFfprobe(),
    ['-v', 'error', '-show_entries', 'format=duration', '-of', 'default=nw=1:nk=1', mediaPath],
    { encoding: 'utf8' },
  );
  if (r.status !== 0) {
    throw new Error(`ffprobe duration failed (status ${r.status}) on ${mediaPath}: ${r.stderr ?? ''}`);
  }
  const seconds = Number((r.stdout ?? '').trim());
  if (!Number.isFinite(seconds) || seconds <= 0) {
    throw new Error(`ffprobe reported a non-positive duration (${r.stdout?.trim()}) for ${mediaPath}`);
  }
  return seconds;
}

/**
 * Synthesise :data:`SPEECH_PHRASE` to `wavPath` via Windows SAPI. Windows-only.
 *
 * `scriptDir` is where the throwaway .ps1 lands (the per-run data root).
 */
export function synthesizeSpeechWav(wavPath: string, scriptDir: string, text = SPEECH_PHRASE): string {
  if (process.platform !== 'win32') {
    throw new Error('synthesizeSpeechWav requires Windows SAPI (System.Speech); guard with test.skip');
  }
  const scriptPath = join(scriptDir, 'sapi-speech.ps1');
  writeFileSync(scriptPath, SAPI_SCRIPT, 'utf8');
  const r = spawnSync(
    'powershell.exe',
    ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', scriptPath, '-Text', text, '-Out', wavPath],
    { encoding: 'utf8' },
  );
  if (r.status !== 0 || !existsSync(wavPath)) {
    throw new Error(
      `SAPI speech synthesis failed (status ${r.status}) -> ${wavPath}\n` +
        `stdout: ${r.stdout ?? ''}\nstderr: ${r.stderr ?? ''}`,
    );
  }
  const voice = /VOICE=(.+)/.exec(r.stdout ?? '')?.[1]?.trim() ?? '';
  if (!voice) throw new Error(`SAPI script did not report a voice; stdout: ${r.stdout ?? ''}`);
  return voice;
}

/**
 * Generate a real H.264/AAC MP4 that CARRIES SPEECH: the same `testsrc` video the
 * silent fixture uses, muxed with a SAPI-synthesised speech track.
 *
 * The video is generated at `ceil(speech) + 2` s and the mux uses `-shortest`, so
 * the output length equals the SPEECH length and the whole phrase is carried. The
 * 3 s silent sample would truncate ~7 s of speech, which is precisely why this
 * does not just reuse it.
 */
export function generateSpeechSample(samplePath: string, workDir: string): SpeechFixture {
  const wavPath = join(workDir, 'speech.wav');
  const voice = synthesizeSpeechWav(wavPath, workDir);
  const speechDurationSec = probeDurationSec(wavPath);
  const videoSec = Math.ceil(speechDurationSec) + 2;
  const args = [
    '-y',
    '-f',
    'lavfi',
    '-i',
    `testsrc=duration=${videoSec}:size=640x360:rate=24`,
    '-i',
    wavPath,
    '-c:v',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-movflags',
    '+faststart',
    '-c:a',
    'aac',
    '-shortest',
    samplePath,
  ];
  const r = spawnSync(process.env.RF_FFMPEG?.trim() || 'ffmpeg', args, { encoding: 'utf8' });
  if (r.status !== 0 || !existsSync(samplePath)) {
    throw new Error(`ffmpeg speech-sample mux failed (status ${r.status}): ${r.stderr ?? ''}`);
  }
  return { wavPath, voice, speechDurationSec };
}

/** Run one JSON-RPC request against a one-shot sidecar process; return result. */
function sidecarCall(python: string, dataRoot: string, method: string, params: unknown): unknown {
  const req = `${JSON.stringify({ jsonrpc: '2.0', id: 1, method, params })}\n`;
  const r = spawnSync(python, ['-m', 'media_studio'], {
    cwd: SIDECAR_DIR,
    input: req,
    encoding: 'utf8',
    env: { ...process.env, MEDIA_STUDIO_CONFIG_DIR: dataRoot },
  });
  const lines = (r.stdout ?? '').split('\n').filter((l) => l.trim().startsWith('{'));
  for (const line of lines) {
    const msg = JSON.parse(line) as { id?: number; result?: unknown; error?: unknown };
    if (msg.id === 1) {
      if (msg.error) throw new Error(`sidecar ${method} error: ${JSON.stringify(msg.error)}`);
      return msg.result;
    }
  }
  throw new Error(`sidecar ${method}: no response (status ${r.status}) stderr=${r.stderr ?? ''}`);
}

/**
 * Writes the seeded sample media into `samplePath`. `workDir` is the per-run data
 * root, for any intermediate the generator needs (e.g. the speech WAV).
 */
export type MediaGenerator = (samplePath: string, workDir: string) => void;

/**
 * Build a fresh data root, generate a real sample MP4, register it through the
 * real sidecar `library.add`, and return everything the launched app needs.
 *
 * `generateMedia` defaults to the silent `testsrc`+`sine` sample, so every
 * existing caller is byte-for-byte unchanged; the transcribe journey passes
 * :func:`generateSpeechSample` to get a SPEECH-bearing sample through the exact
 * same seeding path (same `library.add`, same thumbnail, same env).
 */
export function seedEnvironment(generateMedia: MediaGenerator = generateSample): SeededEnv {
  const python = resolvePython();
  // realpathSync.NATIVE expands the tmp path's 8.3 SHORT name to its LONG form.
  // os.tmpdir() on Windows returns the SHORT name (C:\Users\PREKZU~1\...), which
  // becomes main's DATA_ROOT — but the sidecar canonicalises its thumbnail path to
  // the LONG form (C:\Users\Prekzursil\...). The mstream `thumb:` containment guard
  // (startsWith) then rejects the poster (short root vs long path) → a 404. Plain
  // realpathSync does NOT expand short names (verified); .native does. A real
  // install's %APPDATA% root has no short/long split; canonicalising here matches it.
  const dataRoot = realpathSync.native(mkdtempSync(join(tmpdir(), 'reframe-e2e-data-')));
  const samplePath = join(dataRoot, 'sample.mp4');
  generateMedia(samplePath, dataRoot);

  const added = sidecarCall(python, dataRoot, 'library.add', { path: samplePath }) as {
    video: { id: string };
  };
  const videoId = added.video.id;

  // Generate the source poster frame so the Library card's `thumb:` request resolves
  // instead of 404-ing in the sandboxed renderer. `library.thumbnail` is a SYNC RPC
  // (verified: it runs ffmpeg and writes data_dir/thumbnails/<id>.jpg before
  // returning), so the one-shot sidecarCall completes the write. The app does this
  // on demand (useVideoThumbnail); an out-of-band seed must do it too. Not swallowed:
  // a thumbnail failure is a real setup problem worth surfacing, not hiding.
  sidecarCall(python, dataRoot, 'library.thumbnail', { id: videoId });

  const appEnv = definedEnv({
    MEDIA_STUDIO_PYTHON: python,
    MEDIA_STUDIO_SIDECAR_DIR: SIDECAR_DIR,
    MEDIA_STUDIO_CONFIG_DIR: dataRoot,
  });

  return { dataRoot, samplePath, videoId, python, appEnv };
}

/**
 * Provision assets (a LONG job) by driving a live sidecar until the ensure job
 * reports `job.done`. Unlike `sidecarCall` (one-shot spawnSync, which would kill
 * the download when the RPC returns), this keeps the sidecar alive and streams its
 * stdout until the `assets.ensure` job completes. Used to seed the core reframe
 * model (YuNet) into the data root — the SAME step a real first-run performs —
 * so the default `reframeEngine:"auto"` (claudeshorts) path can actually reframe.
 */
export function provisionAssets(python: string, dataRoot: string, names: string[]): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    const proc = spawn(python, ['-m', 'media_studio'], {
      cwd: SIDECAR_DIR,
      env: { ...process.env, MEDIA_STUDIO_CONFIG_DIR: dataRoot },
    });
    let buf = '';
    let jobId = '';
    // Capture the sidecar's stderr so a SILENT provisioning failure (e.g. a missing
    // download dep -> assets.ensure gracefully SKIPS the item but still reports
    // job.done) is surfaced in the rejection instead of only manifesting later as a
    // mysterious "model not provisioned" at reframe time.
    let stderr = '';
    proc.stderr.setEncoding('utf8');
    proc.stderr.on('data', (chunk: string) => {
      stderr += chunk;
    });
    const timer = setTimeout(() => {
      proc.kill();
      reject(new Error(`provisionAssets(${names.join(',')}) timed out\n${stderr}`));
    }, 300_000);
    const done = (err?: Error): void => {
      clearTimeout(timer);
      proc.kill();
      if (err) reject(err);
      else resolve();
    };
    proc.stdout.setEncoding('utf8');
    proc.stdout.on('data', (chunk: string) => {
      buf += chunk;
      let nl: number;
      while ((nl = buf.indexOf('\n')) >= 0) {
        const line = buf.slice(0, nl).trim();
        buf = buf.slice(nl + 1);
        if (!line.startsWith('{')) continue;
        let msg: {
          id?: number;
          method?: string;
          result?: { jobId?: string };
          params?: { jobId?: string; result?: { installed?: string[] } };
        };
        try {
          msg = JSON.parse(line);
        } catch {
          continue;
        }
        if (msg.id === 1 && msg.result?.jobId) jobId = msg.result.jobId;
        if (msg.params?.jobId === jobId && msg.method === 'job.done') {
          // VERIFY the requested assets actually installed. assets.ensure emits
          // job.done even when it GRACEFULLY SKIPS a failed item (WU C1), so a silent
          // download failure would otherwise pass as success here and only surface
          // as "model not provisioned" deep in the reframe stage.
          const installed = msg.params.result?.installed ?? [];
          const missing = names.filter((n) => !installed.includes(n));
          if (missing.length > 0) {
            done(
              new Error(
                `provisionAssets: ${missing.join(', ')} did not install ` +
                  `(installed=${JSON.stringify(installed)}); sidecar stderr:\n${stderr}`,
              ),
            );
          } else {
            done();
          }
        }
        if (msg.params?.jobId === jobId && msg.method === 'job.error') {
          done(new Error(`provisionAssets job.error: ${JSON.stringify(msg.params)}\n${stderr}`));
        }
      }
    });
    proc.on('error', reject);
    proc.stdin.write(
      `${JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'assets.ensure', params: { names } })}\n`,
    );
  });
}

/**
 * Write settings into the per-run data root through the REAL `settings.set` RPC
 * (the same one the Settings UI calls), returning the merged result.
 *
 * Used by the transcribe journey to PIN the ASR target before the app launches.
 * Not a mock: `SettingsStore.set` merges + persists to `<dataRoot>/settings.json`,
 * which is exactly where `_transcribe_and_persist` reads it from at job time.
 *
 * CONTRACT-NOTE: `settings.set`'s PARAMS OBJECT *is* the value map — the handler
 * is `self.settings.set(dict(params))` (handlers/library_ops.py:382), with no
 * `{values: …}` envelope. Wrapping it would silently persist a `values` key and
 * leave `transcribeModel` unset, which is exactly the kind of no-op setup that
 * makes a test measure nothing.
 */
export function applySettings(
  python: string,
  dataRoot: string,
  values: Record<string, unknown>,
): Record<string, unknown> {
  return sidecarCall(python, dataRoot, 'settings.set', values) as Record<string, unknown>;
}

/** Direct `media.playable` probe (used to label the preview path honestly). */
export function probePlayable(
  python: string,
  dataRoot: string,
  videoId: string,
): { playable: boolean; proxyPath?: string } {
  return sidecarCall(python, dataRoot, 'media.playable', { videoId }) as {
    playable: boolean;
    proxyPath?: string;
  };
}

/**
 * The `resources/bin/ffmpeg` that a PACKAGED artifact actually ships and runs.
 *
 * electron-builder maps `build/ffmpeg/win -> resources/bin` (electron-builder.yml
 * extraResources), and the packaged main process points the sidecar at exactly
 * this path via MEDIA_STUDIO_FFMPEG (`buildSidecarEnv`; see app/main/
 * sidecar.env.test.ts §A3 — `<resourcesPath>/bin/ffmpeg.exe`). So this is THE
 * binary a shipped export runs through, and the only one whose capabilities a
 * packaged smoke may trust. Verified against a real install: an executable at
 * `D:/Program Files/Reframe/Reframe.exe` yields
 * `D:/Program Files/Reframe/resources/bin/ffmpeg.exe`.
 */
export function bundledFfmpegPath(executablePath: string): string {
  return join(dirname(executablePath), 'resources', 'bin', `ffmpeg${process.platform === 'win32' ? '.exe' : ''}`);
}

/**
 * Resolve `ffprobe` for the spec's OWN independent probe of a produced clip.
 * Mirrors generateSample's ffmpeg resolution so the golden journey carries no new
 * precondition beyond the ffmpeg/ffprobe toolchain it already needs: RF_FFPROBE
 * wins; else derive the sibling of RF_FFMPEG (…/ffmpeg[.exe] → …/ffprobe[.exe]);
 * else the packaged MEDIA_STUDIO_FFPROBE; else `ffprobe` on PATH.
 */
export function resolveFfprobe(): string {
  const explicit = process.env.RF_FFPROBE?.trim();
  if (explicit) return explicit;
  const ffmpeg = process.env.RF_FFMPEG?.trim();
  if (ffmpeg) {
    const swapped = ffmpeg.replace(/ffmpeg(\.exe)?$/i, (_m, ext: string | undefined) => `ffprobe${ext ?? ''}`);
    if (swapped !== ffmpeg) return swapped;
  }
  const bundled = process.env.MEDIA_STUDIO_FFPROBE?.trim();
  if (bundled) return bundled;
  return 'ffprobe';
}

/** ffprobe facts read straight off a produced FILE (not the app's shorts.list metadata). */
export interface ProbedVideo {
  width: number;
  height: number;
  vcodec: string;
  pixFmt: string;
  /** Container duration in seconds (real playable length, NOT a metadata field). */
  durationSec: number;
  sizeBytes: number;
  /** null when the produced file carries no audio stream. */
  acodec: string | null;
}

/**
 * Independently `ffprobe` a produced .mp4 — the EXTERNAL done-signal. Deliberately
 * does NOT trust the app's `shorts.list` (which reports durationSec from a sidecar
 * .json and carries no codec), so a truncated / wrong-geometry / non-h264 file
 * cannot masquerade as "a real playable vertical short". Reads geometry + codec +
 * pixel format off the video stream and duration/size off the container.
 */
export function probeVideo(producedPath: string): ProbedVideo {
  const ffprobe = resolveFfprobe();
  const args = [
    '-v', 'error',
    '-show_entries', 'stream=codec_type,codec_name,width,height,pix_fmt',
    '-show_entries', 'format=duration,size',
    '-of', 'json',
    producedPath,
  ];
  const r = spawnSync(ffprobe, args, { encoding: 'utf8' });
  if (r.status !== 0) {
    throw new Error(`ffprobe failed (status ${r.status}) on ${producedPath}: ${r.stderr ?? ''}`);
  }
  const parsed = JSON.parse(r.stdout) as {
    streams?: Array<{
      codec_type?: string;
      codec_name?: string;
      width?: number;
      height?: number;
      pix_fmt?: string;
    }>;
    format?: { duration?: string; size?: string };
  };
  const streams = parsed.streams ?? [];
  const v = streams.find((s) => s.codec_type === 'video');
  const a = streams.find((s) => s.codec_type === 'audio');
  if (!v) throw new Error(`ffprobe found no video stream in ${producedPath}`);
  return {
    width: v.width ?? 0,
    height: v.height ?? 0,
    vcodec: v.codec_name ?? '',
    pixFmt: v.pix_fmt ?? '',
    durationSec: Number(parsed.format?.duration ?? 0),
    sizeBytes: Number(parsed.format?.size ?? 0),
    acodec: a?.codec_name ?? null,
  };
}
