// e2e/fixtures.ts — deterministic test-environment setup for the Reframe GUI E2E.
//
// Builds a throwaway, per-run data root and seeds it with ONE real sample video
// so the launched Electron app shows a library entry to open + preview. Nothing
// here mocks the app: the sample is a genuine H.264/AAC MP4 generated by ffmpeg,
// and it is registered through the SAME `library.add` JSON-RPC the running app
// would call (driven against the real Python sidecar), so `media.playable`
// resolves it to the source path and the mstream protocol streams real bytes.
//
// Why seed out-of-band instead of clicking "Add videos": the add path goes
// through a NATIVE OS file dialog (dialog.openVideos), which Playwright cannot
// drive headlessly. Seeding the data root the sidecar reads is equivalent — the
// app lists + opens + plays the exact same library record either way.

import { spawnSync } from 'node:child_process';
import { mkdtempSync, existsSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { findLatestBuild, parseElectronApp } from 'electron-playwright-helpers';

// ESM (the app package is "type": "module"): derive __dirname from import.meta.
const HERE = dirname(fileURLToPath(import.meta.url));

/** Absolute path to the repo root (two levels up from app/e2e). */
export const REPO_ROOT = resolve(HERE, '..', '..');
/** The Python sidecar package dir (cwd for `-m media_studio`). */
export const SIDECAR_DIR = join(REPO_ROOT, 'sidecar');
/** The built main-process entry the launched Electron app boots (DEV build). */
export const MAIN_ENTRY = join(REPO_ROOT, 'app', 'out', 'main', 'main.js');
/** electron-builder packaged-artifact output dir (electron-builder.yml). */
export const DIST_DIR = join(REPO_ROOT, 'dist');

/**
 * What the launched app boots: the args + (for a real package) the executable
 * path, plus whether we are pointing at a PACKAGED artifact or the dev build.
 */
export interface BuiltApp {
  /** Launch args ([appInfo.main] for a package, [MAIN_ENTRY] for dev). */
  main: string;
  /** electron-builder executable path; undefined => use the dev electron bin. */
  executablePath?: string;
  /** True when resolved to a real electron-builder package (the shipped .exe). */
  packaged: boolean;
}

/**
 * Resolve the app under test, PREFERRING a real electron-builder package so the
 * E2E drives the SHIPPED binary (the .exe on Windows). If RF_E2E_DEV is set, or
 * no package exists in `dist/`, fall back to the dev build (out/main/main.js) so
 * the same spec still gives local GUI coverage. Set RF_E2E_REQUIRE_PACKAGED=1 to
 * make the absence of a package a hard error (the packaged.spec.ts CI leg).
 */
export function findBuiltApp(): BuiltApp {
  const requirePackaged = process.env.RF_E2E_REQUIRE_PACKAGED === '1';
  // RF_E2E_DEV forces the dev build (used to run preview.spec's data-pipeline
  // against the dev build on the Windows leg). But packaged.spec self-sets
  // RF_E2E_REQUIRE_PACKAGED in the SAME process — that ALWAYS wins, so the
  // packaged-only spec still drives the real .exe even when RF_E2E_DEV is set.
  const wantDev = !requirePackaged && process.env.RF_E2E_DEV === '1';
  if (!wantDev && existsSync(DIST_DIR)) {
    const diag: string[] = [];
    // electron-builder writes its UNPACKED app tree to a per-platform dir
    // (win-unpacked / linux-unpacked / mac[-arm64]); the installers (.exe/.zip)
    // sit beside it. parseElectronApp needs the UNPACKED dir, not an installer.
    // Try the deterministic dirs first, then fall back to findLatestBuild
    // (which itself only accepts a "<platform>-…" DIRECTORY, never an installer).
    const candidates = ['win-unpacked', 'linux-unpacked', 'mac', 'mac-arm64'];
    for (const candidate of candidates) {
      const dir = join(DIST_DIR, candidate);
      if (!existsSync(dir)) continue;
      try {
        const info = parseElectronApp(dir);
        // Only the EXECUTABLE must exist on disk. info.main is the app entry as
        // electron.launch wants it — for an asar build that is a path INSIDE
        // app.asar (e.g. resources/app.asar/out/main/main.js), which existsSync()
        // always reports false even though Electron resolves it fine; never gate
        // on it.
        if (existsSync(info.executable)) {
          return { main: info.main, executablePath: info.executable, packaged: true };
        }
        diag.push(`${candidate}: parsed but executable missing (${info.executable})`);
      } catch (err) {
        const inside = readdirSync(dir).slice(0, 20).join(',');
        diag.push(`${candidate}: ${(err as Error).message} [contains: ${inside}]`);
      }
    }
    try {
      const latest = findLatestBuild(DIST_DIR);
      const info = parseElectronApp(latest);
      if (existsSync(info.executable)) {
        return { main: info.main, executablePath: info.executable, packaged: true };
      }
      diag.push(`findLatestBuild(${latest}): executable missing (${info.executable})`);
    } catch (err) {
      diag.push(`findLatestBuild: ${(err as Error).message}`);
    }
    if (requirePackaged) {
      const listing = readdirSync(DIST_DIR).join(', ');
      throw new Error(
        `electron-builder output present under ${DIST_DIR} but no launchable package resolved ` +
          `(RF_E2E_REQUIRE_PACKAGED=1). dist contents: [${listing}]. attempts: ${diag.join(' | ')}`,
      );
    }
  }
  if (requirePackaged) {
    throw new Error(
      `no electron-builder output dir found at ${DIST_DIR} (RF_E2E_REQUIRE_PACKAGED=1). ` +
        'Run electron-builder before this packaged-only leg.',
    );
  }
  if (!existsSync(MAIN_ENTRY)) {
    throw new Error(`built main entry missing: ${MAIN_ENTRY} — run \`npm run build\` first`);
  }
  return { main: MAIN_ENTRY, packaged: false };
}

/**
 * The Python 3.12 interpreter to run the sidecar with. RF_PY (set by the test
 * runner / CI) wins; otherwise the Windows `py -3.12` launcher is resolved to a
 * concrete executable so the SAME interpreter seeds the library AND backs the
 * launched app (a single MEDIA_STUDIO_PYTHON value).
 */
export function resolvePython(): string {
  const fromEnv = process.env.RF_PY?.trim();
  if (fromEnv) return fromEnv;
  const probe = spawnSync('py', ['-3.12', '-c', 'import sys;print(sys.executable)'], {
    encoding: 'utf8',
  });
  const out = probe.stdout?.trim();
  if (probe.status === 0 && out) return out;
  // POSIX / CI fallback.
  return 'python3';
}

export interface SeededEnv {
  /** Fresh per-run data root (MEDIA_STUDIO_CONFIG_DIR). */
  dataRoot: string;
  /** Absolute path to the generated sample MP4. */
  samplePath: string;
  /** Library id assigned to the sample by `library.add`. */
  videoId: string;
  /** Python interpreter path used for the sidecar. */
  python: string;
  /** The env the launched Electron app must inherit (no undefined values). */
  appEnv: Record<string, string>;
}

/** Drop undefined values so the env satisfies Playwright's `{[k]: string}`. */
function definedEnv(extra: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(process.env)) {
    if (typeof v === 'string') out[k] = v;
  }
  return { ...out, ...extra };
}

/** Generate a real 3s H.264/AAC MP4 (faststart) Chromium can decode. */
function generateSample(samplePath: string): void {
  const args = [
    '-y',
    '-f',
    'lavfi',
    '-i',
    'testsrc=duration=3:size=640x360:rate=24',
    '-f',
    'lavfi',
    '-i',
    'sine=frequency=440:duration=3',
    '-c:v',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-movflags',
    '+faststart',
    '-c:a',
    'aac',
    '-shortest',
    samplePath,
  ];
  const r = spawnSync(process.env.RF_FFMPEG?.trim() || 'ffmpeg', args, { encoding: 'utf8' });
  if (r.status !== 0 || !existsSync(samplePath)) {
    throw new Error(`ffmpeg sample generation failed (status ${r.status}): ${r.stderr ?? ''}`);
  }
}

/** Run one JSON-RPC request against a one-shot sidecar process; return result. */
function sidecarCall(python: string, dataRoot: string, method: string, params: unknown): unknown {
  const req = `${JSON.stringify({ jsonrpc: '2.0', id: 1, method, params })}\n`;
  const r = spawnSync(python, ['-m', 'media_studio'], {
    cwd: SIDECAR_DIR,
    input: req,
    encoding: 'utf8',
    env: { ...process.env, MEDIA_STUDIO_CONFIG_DIR: dataRoot },
  });
  const lines = (r.stdout ?? '').split('\n').filter((l) => l.trim().startsWith('{'));
  for (const line of lines) {
    const msg = JSON.parse(line) as { id?: number; result?: unknown; error?: unknown };
    if (msg.id === 1) {
      if (msg.error) throw new Error(`sidecar ${method} error: ${JSON.stringify(msg.error)}`);
      return msg.result;
    }
  }
  throw new Error(`sidecar ${method}: no response (status ${r.status}) stderr=${r.stderr ?? ''}`);
}

/**
 * Build a fresh data root, generate a real sample MP4, register it through the
 * real sidecar `library.add`, and return everything the launched app needs.
 */
export function seedEnvironment(): SeededEnv {
  const python = resolvePython();
  const dataRoot = mkdtempSync(join(tmpdir(), 'reframe-e2e-data-'));
  const samplePath = join(dataRoot, 'sample.mp4');
  generateSample(samplePath);

  const added = sidecarCall(python, dataRoot, 'library.add', { path: samplePath }) as {
    video: { id: string };
  };
  const videoId = added.video.id;

  const appEnv = definedEnv({
    MEDIA_STUDIO_PYTHON: python,
    MEDIA_STUDIO_SIDECAR_DIR: SIDECAR_DIR,
    MEDIA_STUDIO_CONFIG_DIR: dataRoot,
  });

  return { dataRoot, samplePath, videoId, python, appEnv };
}

/** Direct `media.playable` probe (used to label the preview path honestly). */
export function probePlayable(
  python: string,
  dataRoot: string,
  videoId: string,
): { playable: boolean; proxyPath?: string } {
  return sidecarCall(python, dataRoot, 'media.playable', { videoId }) as {
    playable: boolean;
    proxyPath?: string;
  };
}
