"""Vendored TransNetV2 shot-transition network (soCzech/TransNetV2, MIT).

PRODUCTION VENDORING (WU B4): the PyTorch network is vendored here from
``soCzech/TransNetV2`` ``inference-pytorch/transnetv2_pytorch.py`` (GitHub, **MIT**
— see the sibling ``LICENSE``, redistribution permitted). The upstream GitHub repo
ships NO ``.pth`` (it is generated by ``convert_weights.py`` from the TF
SavedModel); the re-hosted ``transnetv2.safetensors`` weight (WU I1) is a standard
such conversion at the network's DEFAULT config, so ``TransNetV2()`` +
``load_state_dict`` matches by construction.

This package ``__init__`` is intentionally **light** — it imports NOTHING heavy
(no torch). The model module (:mod:`.transnetv2_pytorch`) imports torch at module
top (an ``nn.Module`` subclass needs ``torch.nn`` at class-definition time), so it
is imported LAZILY only from
:mod:`media_studio.features.scene_transnet_backend.RealTransNetBackend` and NEVER
at package import or during the test suite. Every top-level statement in that
module carries ``# pragma: no cover``; being never imported under the coverage run
it reports zero measurable statements and never perturbs the 100% gate (mirrors
the ``_lightasd`` heavy-seam convention).
"""

from __future__ import annotations

#: Upstream source coordinates (provenance for the vendored TransNetV2 network).
TRANSNETV2_UPSTREAM = "https://github.com/soCzech/TransNetV2"
TRANSNETV2_LICENSE = "MIT"
#: The re-host weight basename the backend loads (verify-before-load: safetensors).
TRANSNETV2_WEIGHT_NAME = "transnetv2.safetensors"

__all__ = [
    "TRANSNETV2_LICENSE",
    "TRANSNETV2_UPSTREAM",
    "TRANSNETV2_WEIGHT_NAME",
]
