"""Generate every derived contract artifact from :mod:`contract.spec`.

Run from the ``sidecar/`` directory::

    python -m contract.generate            # (re)write all artifacts
    python -m contract.generate --check    # verify committed artifacts are current

Emitted artifacts:
  * ``sidecar/contract/generated/contract.schema.json`` — the canonical machine
    contract (methods + JSON Schemas + needs-key set + settings). Byte-stable
    (no formatter touches sidecar JSON), so its regeneration is compared
    byte-for-byte by the staleness gate.
  * ``app/renderer/src/lib/rpc/generated/schemas.generated.ts`` — the §3 data
    interfaces + the ``MethodName`` union.
  * ``app/renderer/src/lib/rpc/generated/client.generated.ts`` — the method-typed
    client wrappers over the existing ``rpc()`` runtime.
  * ``app/renderer/src/lib/rpc/generated/needsKeyInjection.generated.ts`` — the
    key-injection Set + predicate (the twin of ``keyBridge.ts``).

Each TS file carries a ``contract-source-sha256`` header equal to the hash of the
canonical contract, so the staleness gate can prove the TS was generated from the
CURRENT spec without being coupled to the Biome formatter's byte output.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import sys
import typing
from pathlib import Path
from typing import Any

from . import schema, spec

_GEN_HEADER = "@generated by sidecar/contract/generate.py — DO NOT EDIT BY HAND."
_REGEN_HINT = "Regenerate: `python -m contract.generate` (run from sidecar/)."

_CONTRACT_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _CONTRACT_DIR.parents[1]
_JSON_PATH = _CONTRACT_DIR / "generated" / "contract.schema.json"
_TS_DIR = _REPO_ROOT / "app" / "renderer" / "src" / "lib" / "rpc" / "generated"


# --------------------------------------------------------------------------- #
# Canonical contract dict + hash
# --------------------------------------------------------------------------- #


def build_contract() -> dict[str, Any]:
    """Build the canonical contract dict (the source of both JSON and TS)."""
    methods: list[dict[str, Any]] = []
    for m in spec.METHODS:
        params_schema = schema.dataclass_json_schema(m.params) if m.params is not None else None
        methods.append(
            {
                "name": m.name,
                "kind": m.kind,
                "needsKey": m.needs_key,
                "paramsSchema": params_schema,
            }
        )
    settings_schema = schema.dataclass_json_schema(spec.Settings)
    settings_defaults = schema.dataclass_defaults(spec.Settings)
    contract: dict[str, Any] = {
        "version": "v1.5-poc",
        "methodNames": list(spec.method_names()),
        "needsKeyInjection": list(spec.needs_key_names()),
        "methods": methods,
        "settingsSchema": settings_schema,
        "settingsDefaults": settings_defaults,
    }
    contract["sourceSha256"] = _hash_contract(contract)
    return contract


def _hash_contract(contract: dict[str, Any]) -> str:
    """A stable SHA-256 over the contract, excluding the hash field itself."""
    body = {k: v for k, v in contract.items() if k != "sourceSha256"}
    canonical = json.dumps(body, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def render_json(contract: dict[str, Any]) -> str:
    """Render the canonical JSON artifact (deterministic, trailing newline)."""
    return json.dumps(contract, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


# --------------------------------------------------------------------------- #
# TypeScript emission (Biome-conformant: 2-space, single quotes, semicolons,
# trailing commas, LF). The staleness gate checks the embedded source hash, not
# the byte output, so Biome may reflow freely without a false drift failure.
# --------------------------------------------------------------------------- #


def _ts_header(sha: str, summary: str) -> str:
    return f"// {_GEN_HEADER}\n// {_REGEN_HINT}\n// contract-source-sha256: {sha}\n//\n// {summary}\n"


def _ts_interface(cls: type) -> str:
    lines = [f"export interface {cls.__name__} {{"]
    for name, ts_type, optional in schema.dataclass_ts_fields(cls):
        opt = "?" if optional else ""
        lines.append(f"  {name}{opt}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def _ts_method_name_union() -> str:
    names = spec.method_names()
    lines = ["export type MethodName ="]
    for i, name in enumerate(names):
        terminator = ";" if i == len(names) - 1 else ""
        lines.append(f"  | '{name}'{terminator}")
    return "\n".join(lines)


def render_schemas_ts(contract: dict[str, Any]) -> str:
    header = _ts_header(
        contract["sourceSha256"],
        "The §3 data interfaces + the MethodName union (field names = frozen wire names).",
    )
    blocks = [_ts_interface(model) for model in spec.DATA_MODELS]
    blocks.append("/** Every method name in the v1.5 contract (POC slice). */\n" + _ts_method_name_union())
    return header + "\n" + "\n\n".join(blocks) + "\n"


def _ts_default_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return f"'{value}'"
    if value is None:
        return "undefined"
    return str(value)


def _named_arg_specs(params: type) -> list[tuple[str, str, bool, Any]]:
    """Return ``(name, ts_type, has_default, default)`` per params field."""
    hints = typing.get_type_hints(params)
    out: list[tuple[str, str, bool, Any]] = []
    for f in dataclasses.fields(params):
        annotation = hints[f.name]
        inner = schema.optional_inner(annotation)
        ts_type = schema.ts_type_for_type(inner if inner is not None else annotation)
        has_default = f.default is not dataclasses.MISSING
        out.append((f.name, ts_type, has_default, f.default))
    return out


def _wrapper_signature_arrow(m: spec.MethodSpec) -> tuple[str, str]:
    """Return ``(params_list, body)`` for a wrapper's ``(params) => body``."""
    if m.binding is spec.Binding.NONE:
        return "", f"rpc('{m.name}')"
    if m.binding is spec.Binding.SPREAD:
        type_name = m.params.__name__ if m.params is not None else "unknown"
        return f"values: Partial<{type_name}>", f"rpc('{m.name}', values)"
    assert m.params is not None  # NAMED always has params
    args = _named_arg_specs(m.params)
    parts: list[str] = []
    for name, ts_type, has_default, default in args:
        if has_default:
            parts.append(f"{name} = {_ts_default_literal(default)}")
        else:
            parts.append(f"{name}: {ts_type}")
    keys = ", ".join(name for name, _t, _d, _v in args)
    return ", ".join(parts), f"rpc('{m.name}', {{ {keys} }})"


def _render_wrapper(m: spec.MethodSpec, indent: str) -> str:
    """Render one leaf wrapper ``name: (args): Promise<R> => body,`` at ``indent``."""
    leaf = m.ts_path[-1]
    params_list, body = _wrapper_signature_arrow(m)
    return f"{indent}{leaf}: ({params_list}): Promise<{m.result_ts}> => {body},"


def render_client_ts(contract: dict[str, Any]) -> str:
    header = _ts_header(
        contract["sourceSha256"],
        "Method-typed client wrappers over the existing rpc() runtime (POC slice).",
    )
    own: set[str] = set()
    hand: set[str] = set()
    for m in spec.METHODS:
        for type_name, module in m.result_imports:
            (own if module == "./schemas.generated" else hand).add(type_name)
    # Param types referenced in wrapper signatures also need importing.
    own.update({"Settings", "ShortmakerControls"})
    imports = ["import { rpc } from '../client';"]
    if own:
        imports.append(f"import type {{ {', '.join(sorted(own))} }} from './schemas.generated';")
    if hand:
        imports.append(f"import type {{ {', '.join(sorted(hand))} }} from '../schemas';")

    # Group leaf methods under their first path segment; ``ping`` is top-level.
    groups: dict[str, list[spec.MethodSpec]] = {}
    top: list[spec.MethodSpec] = []
    for m in spec.METHODS:
        if len(m.ts_path) == 1:
            top.append(m)
        else:
            groups.setdefault(m.ts_path[0], []).append(m)

    body_lines: list[str] = ["export const clientGenerated = {"]
    for m in top:
        body_lines.append(_render_wrapper(m, "  "))
    for group in sorted(groups):
        body_lines.append("")
        body_lines.append(f"  {group}: {{")
        for m in groups[group]:
            body_lines.append(_render_wrapper(m, "    "))
        body_lines.append("  },")
    body_lines.append("} as const;")
    body = "\n".join(body_lines)
    return header + "\n" + "\n".join(imports) + "\n\n" + body + "\n\nexport default clientGenerated;\n"


def render_needskey_ts(contract: dict[str, Any]) -> str:
    header = _ts_header(
        contract["sourceSha256"],
        "The key-injection Set + predicate — the generated twin of keyBridge.ts.",
    )
    names = contract["needsKeyInjection"]
    entries = "".join(f"  '{n}',\n" for n in names)
    body = (
        "/** Methods whose sidecar handler needs live provider keys injected. */\n"
        f"export const NEEDS_KEY_INJECTION: ReadonlySet<string> = new Set([\n{entries}]);\n\n"
        "/** True when `method`'s handler needs key injection (generated from the contract). */\n"
        "export function needsKeyInjection(method: string): boolean {\n"
        "  return NEEDS_KEY_INJECTION.has(method);\n"
        "}\n"
    )
    return header + "\n" + body


# --------------------------------------------------------------------------- #
# Write / check
# --------------------------------------------------------------------------- #


def _artifacts(contract: dict[str, Any]) -> dict[Path, str]:
    return {
        _JSON_PATH: render_json(contract),
        _TS_DIR / "schemas.generated.ts": render_schemas_ts(contract),
        _TS_DIR / "client.generated.ts": render_client_ts(contract),
        _TS_DIR / "needsKeyInjection.generated.ts": render_needskey_ts(contract),
    }


def write_all() -> list[Path]:
    """(Re)write every artifact. Returns the written paths."""
    contract = build_contract()
    written: list[Path] = []
    for path, text in _artifacts(contract).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path)
    return written


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else ""


def check() -> list[str]:
    """Return a list of drift problems (empty when every artifact is current).

    The JSON artifact is compared byte-for-byte (it is formatter-immune). Each TS
    artifact is checked by its embedded ``contract-source-sha256`` header, so a
    Biome reflow never trips a false drift while a spec change still fails until
    the TS is regenerated.
    """
    contract = build_contract()
    problems: list[str] = []
    expected_json = render_json(contract)
    if _read(_JSON_PATH) != expected_json:
        problems.append(f"stale/missing: {_JSON_PATH.name} (run `python -m contract.generate`)")
    marker = f"contract-source-sha256: {contract['sourceSha256']}"
    for name in ("schemas.generated.ts", "client.generated.ts", "needsKeyInjection.generated.ts"):
        text = _read(_TS_DIR / name)
        if marker not in text:
            problems.append(f"stale/missing: {name} (source hash mismatch — regenerate)")
    return problems


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if "--check" in args:
        problems = check()
        if problems:
            print("contract.generate --check: DRIFT")
            for p in problems:
                print(f"  - {p}")
            return 1
        print("contract.generate --check: OK (artifacts current)")
        return 0
    written = write_all()
    print(f"contract.generate: wrote {len(written)} artifacts")
    for path in written:
        print(f"  - {path.relative_to(_REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
