"""WU C4 — pinned, fully-hashed lockfile for the pip ``--target`` env install.

Verify-before-exec over the FULL transitive closure: the env installer can be
pointed at a hashed lockfile and then runs
``pip install --require-hashes --only-binary=:all: --no-deps -r <lock>`` so every
wheel's bytes are hash-checked before pip unpacks/executes them (top-level pins
alone still pull UNHASHED transitives — the gap C4 closes).

Real hash generation needs network (PyPI + the cu128 torch index) and is a
documented F1 build-prep step (like the ffmpeg binary): these tests exercise the
installer flag path, the lock-shape validator, and the lock-generation argv
builder with NO pip and NO network.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest
from media_studio.assets import manifest
from media_studio.assets.manager import (
    HASHED_LOCK_PIP_ARGS,
    AssetError,
    build_env_install_argvs,
    validate_hashed_lock,
)

# A minimal, well-formed pip-compile ``--generate-hashes`` fragment (the exact
# shape F1 produces): a requirement line ending in `` \``, then indented
# ``--hash=`` continuation lines, then dropped ``# via`` comments.
GOOD_LOCK = """\
# generated by the F1 lock-gen step — DO NOT EDIT BY HAND
--extra-index-url https://download.pytorch.org/whl/cu128
numpy==2.5.0 \\
    --hash=sha256:1111111111111111111111111111111111111111111111111111111111111111 \\
    --hash=sha256:2222222222222222222222222222222222222222222222222222222222222222
    # via
    #   -r requirements-sidecar.txt
httpx==0.28.1 \\
    --hash=sha256:3333333333333333333333333333333333333333333333333333333333333333
    # via -r requirements-sidecar.txt
"""


# --------------------------------------------------------------------------- #
# validate_hashed_lock — the lock-shape gate (TESTS-FIRST red item (a))
# --------------------------------------------------------------------------- #
class TestValidateHashedLock:
    def test_valid_hashed_lock_returns_pins(self):
        pins = validate_hashed_lock(GOOD_LOCK)
        assert pins == ("numpy==2.5.0", "httpx==0.28.1")

    def test_allows_index_option_lines(self):
        # the cu128 torch index is a STILL-HASHED per-index exception: a custom
        # index URL is allowed, but its wheels are hash-verified all the same.
        pins = validate_hashed_lock(
            "--extra-index-url https://download.pytorch.org/whl/cu128\n"
            "torch==2.10.0+cu128 \\\n"
            "    --hash=sha256:"
            + "a" * 64
            + "\n"
        )
        assert pins == ("torch==2.10.0+cu128",)

    def test_unhashed_requirement_is_rejected(self):
        with pytest.raises(AssetError, match="missing --hash"):
            validate_hashed_lock("numpy==2.5.0\n")

    def test_unpinned_requirement_is_rejected(self):
        with pytest.raises(AssetError, match="not pinned"):
            validate_hashed_lock("numpy>=2.0 \\\n    --hash=sha256:" + "b" * 64 + "\n")

    def test_unknown_option_is_rejected(self):
        with pytest.raises(AssetError, match="unsupported"):
            validate_hashed_lock("--find-links ./wheels\nnumpy==2.5.0\n")

    def test_empty_lock_is_rejected(self):
        with pytest.raises(AssetError, match="no pinned requirements"):
            validate_hashed_lock("# only a comment\n\n")

    def test_trailing_continuation_without_final_newline_is_flushed(self):
        # a body whose LAST line still ends with `` \`` (no terminating line):
        # the pending logical-line buffer must still be flushed + validated.
        pins = validate_hashed_lock("numpy==2.5.0 --hash=sha256:" + "e" * 64 + " \\")
        assert pins == ("numpy==2.5.0",)

    def test_the_shipped_lock_is_full_closure_but_not_yet_hashed(self):
        # DOCUMENTS the F1 gap: sidecar/requirements.lock.txt is the FULL
        # transitive closure today but carries NO hashes (it feeds osv-scanner).
        # The validator must therefore REJECT it — proving the gate is real and
        # that hashing it is outstanding F1 build-prep. When F1 regenerates it
        # WITH --generate-hashes, flip this to assert it passes.
        lock = (Path(__file__).resolve().parent.parent / "requirements.lock.txt").read_text(encoding="utf-8")
        with pytest.raises(AssetError, match="missing --hash"):
            validate_hashed_lock(lock)


# --------------------------------------------------------------------------- #
# build_env_install_argvs — the installer flag path (TESTS-FIRST red item (b))
# --------------------------------------------------------------------------- #
class TestHashedLockArgv:
    def test_lock_file_switches_step2_to_require_hashes(self, tmp_path):
        lock = tmp_path / "env.lock.txt"
        steps = build_env_install_argvs(
            "py", tmp_path / "gp.py", tmp_path / "env", ("numpy==2.5.0",), lock_file=lock
        )
        step2 = steps[1]["argv"]
        # the hardening trio is present, in order, before the -r lock ref
        for flag in HASHED_LOCK_PIP_ARGS:
            assert flag in step2
        assert step2[-2:] == ["-r", str(lock)]
        # NO inline requirement leaks onto the argv — the lock is the sole source
        assert "numpy==2.5.0" not in step2

    def test_hardening_trio_constant(self):
        assert HASHED_LOCK_PIP_ARGS == ("--require-hashes", "--only-binary=:all:", "--no-deps")

    def test_without_lock_file_keeps_inline_pins_unchanged(self, tmp_path):
        steps = build_env_install_argvs("py", tmp_path / "gp.py", tmp_path / "env", ("numpy==2.5.0",))
        step2 = steps[1]["argv"]
        assert "numpy==2.5.0" in step2
        assert "--require-hashes" not in step2
        assert "-r" not in step2


# --------------------------------------------------------------------------- #
# AssetEntry.lock_file — the manifest wiring seam (F1 activation point)
# --------------------------------------------------------------------------- #
class TestManifestLockFileField:
    def test_env_asset_may_declare_a_lock_file(self):
        entry = manifest.AssetEntry(
            name="x-env",
            kind="env",
            size_mb=1,
            dest="envs/x",
            installer="env",
            requirements=("numpy==2.5.0",),
            lock_file="requirements-x.lock.txt",
        )
        assert entry.lock_file == "requirements-x.lock.txt"

    def test_lock_file_on_a_non_env_installer_is_rejected(self):
        with pytest.raises(ValueError, match="lock_file"):
            manifest.AssetEntry(
                name="x-dl",
                kind="model",
                size_mb=1,
                dest="x.bin",
                url="https://example.test/x.bin",
                sha256="c" * 64,
                lock_file="nope.lock.txt",
            )

    def test_default_is_none(self):
        entry = manifest.AssetEntry(
            name="y-env", kind="env", size_mb=1, dest="envs/y", installer="env", requirements=("numpy==2.5.0",)
        )
        assert entry.lock_file is None


# --------------------------------------------------------------------------- #
# _install_env wiring — use the lock when staged, LOUD-fallback when absent
# --------------------------------------------------------------------------- #
def _env_entry(tmp_path: Path, lock_file: str | None) -> Any:
    return manifest.AssetEntry(
        name="probe-env",
        kind="env",
        size_mb=1,
        dest="envs/probe",
        installer="env",
        requirements=("numpy==2.5.0",),
        lock_file=lock_file,
    )


class _StubMgr:
    """Drive AssetManager._install_env with fully faked seams (no pip/network)."""

    @staticmethod
    def make(tmp_path: Path):
        from media_studio.assets.manager import AssetManager

        mgr = AssetManager(root=tmp_path / "root")
        # get-pip already staged so _install_env never downloads.
        gp = tmp_path / "root" / "tools" / "get-pip.py"
        gp.parent.mkdir(parents=True, exist_ok=True)
        gp.write_text("# gp", encoding="utf-8")
        calls: list[list[str]] = []

        def fake_run(argv, extra_env=None):
            calls.append(list(argv))
            return 0, ""

        mgr._run_cmd = fake_run  # type: ignore[assignment]
        return mgr, calls


class TestInstallEnvUsesLock:
    def test_staged_lock_drives_require_hashes_install(self, tmp_path, caplog):
        lock = tmp_path / "root" / "envs-locks" / "probe.lock.txt"
        lock.parent.mkdir(parents=True, exist_ok=True)
        lock.write_text("numpy==2.5.0 \\\n    --hash=sha256:" + "d" * 64 + "\n", encoding="utf-8")
        mgr, calls = _StubMgr.make(tmp_path)
        entry = _env_entry(tmp_path, lock_file="envs-locks/probe.lock.txt")
        mgr._install_env(entry, on_frac=lambda *_a: None, should_cancel=lambda: False)
        step2 = calls[1]
        assert "--require-hashes" in step2
        assert step2[-2:] == ["-r", str(lock)]

    def test_declared_but_unstaged_lock_falls_back_loudly(self, tmp_path):
        import logging

        from media_studio.assets import manager as manager_mod

        messages: list[str] = []
        handler = logging.Handler()
        handler.emit = lambda record: messages.append(record.getMessage())  # type: ignore[method-assign]
        manager_mod.log.addHandler(handler)
        try:
            mgr, calls = _StubMgr.make(tmp_path)
            entry = _env_entry(tmp_path, lock_file="envs-locks/missing.lock.txt")
            mgr._install_env(entry, on_frac=lambda *_a: None, should_cancel=lambda: False)
        finally:
            manager_mod.log.removeHandler(handler)
        # LOUD, not silent: the fallback to the (unhashed-transitive) inline pins
        # is logged, and the install still proceeds with the inline requirements.
        joined = " ".join(messages)
        assert "hashed lock" in joined and "falling back" in joined
        assert "numpy==2.5.0" in calls[1]
        assert "--require-hashes" not in calls[1]

    def test_absolute_lock_path_is_used_verbatim(self, tmp_path):
        # an ABSOLUTE entry.lock_file is used as-is (not joined under the root).
        lock = tmp_path / "elsewhere" / "abs.lock.txt"
        lock.parent.mkdir(parents=True, exist_ok=True)
        lock.write_text("numpy==2.5.0 \\\n    --hash=sha256:" + "f" * 64 + "\n", encoding="utf-8")
        mgr, calls = _StubMgr.make(tmp_path)
        entry = _env_entry(tmp_path, lock_file=str(lock))
        mgr._install_env(entry, on_frac=lambda *_a: None, should_cancel=lambda: False)
        assert calls[1][-2:] == ["-r", str(lock)]
        assert "--require-hashes" in calls[1]

    def test_no_lock_declared_keeps_inline_pins(self, tmp_path):
        mgr, calls = _StubMgr.make(tmp_path)
        entry = _env_entry(tmp_path, lock_file=None)
        mgr._install_env(entry, on_frac=lambda *_a: None, should_cancel=lambda: False)
        assert "numpy==2.5.0" in calls[1]
        assert "--require-hashes" not in calls[1]

    def test_staged_lock_that_is_not_hashed_fails_loud(self, tmp_path):
        bad = tmp_path / "root" / "envs-locks" / "probe.lock.txt"
        bad.parent.mkdir(parents=True, exist_ok=True)
        bad.write_text("numpy==2.5.0\n", encoding="utf-8")  # pinned but UNHASHED
        mgr, _calls = _StubMgr.make(tmp_path)
        entry = _env_entry(tmp_path, lock_file="envs-locks/probe.lock.txt")
        with pytest.raises(AssetError, match="missing --hash"):
            mgr._install_env(entry, on_frac=lambda *_a: None, should_cancel=lambda: False)
