// surfaces.visual.spec.ts — VISUAL screenshot-diff baselines for the rest of the
// Wave-2b surfaces (Library is its own spike in library.visual.spec.ts):
//
//   * Create tab           (the global generated-Shorts gallery + ShortMaker),
//   * Director tab         (the prompt-driven AI editing panel),
//   * Repurpose tab        (batch/template/export-preset surface),
//   * Settings → Models & System   (panels/ModelsSystemPanel),
//   * Settings → Providers & Keys  (features/ProvidersKeys — hosts SpendCap),
//   * Settings → Providers & Keys → Spend-cap UI (scoped to the SpendCap card),
//   * Workspace preview    (the per-video Workspace with the <video> masked).
//
// One launched app navigates all surfaces in order (workers:1). Determinism +
// masking + viewport pinning live in _visualSetup.ts. Baselines are Windows-only
// (`*-win32.png`) and generated by `npm run test:e2e:visual:update`.

import { test, expect, type Page } from '@playwright/test';
import {
  launchSeededApp,
  prepareWindow,
  shotOptions,
  openTopTab,
  openVideo,
  openSettingsSection,
  type LaunchedApp,
} from './_visualSetup';

let launched: LaunchedApp;
let win: Page;

test.beforeAll(async () => {
  launched = await launchSeededApp();
  win = await prepareWindow(launched.app);
});

test.afterAll(async () => {
  await launched?.app.close();
});

test('Create tab — Shorts gallery + ShortMaker', async () => {
  await openTopTab(win, 'Create');
  // The Create surface is the Shorts view; its root container marks the gallery.
  await expect(win.locator('.shorts, .create')).toBeVisible();
  await expect(win).toHaveScreenshot('create.png', shotOptions(win));
});

test('Director tab — AI editing panel', async () => {
  await openTopTab(win, 'Director');
  // Lazy panel: wait for the real Director section (not the Suspense fallback).
  await expect(win.locator('section.director-panel')).toBeVisible();
  await expect(win).toHaveScreenshot('director.png', shotOptions(win));
});

test('Repurpose tab — batch / templates / export presets', async () => {
  await openTopTab(win, 'Repurpose');
  await expect(
    win.locator('.toptab[aria-selected="true"]', { hasText: 'Repurpose' }),
  ).toBeVisible();
  await expect(win).toHaveScreenshot('repurpose.png', shotOptions(win));
});

test('Settings → Models & System panel', async () => {
  await openSettingsSection(win, 'Models & System');
  await expect(win.locator('section.models-system-panel')).toBeVisible();
  await expect(win).toHaveScreenshot('settings-models-system.png', shotOptions(win));
});

test('Settings → Providers & Keys panel', async () => {
  await openSettingsSection(win, 'Providers & Keys');
  await expect(win.locator('section.providers-keys')).toBeVisible();
  await expect(win).toHaveScreenshot('settings-providers-keys.png', shotOptions(win));
});

test('Spend-cap UI (scoped to the SpendCap card on Providers & Keys)', async () => {
  await openSettingsSection(win, 'Providers & Keys');
  // SpendCap renders inside ProvidersKeys; snapshot the card alone for a tight,
  // low-noise diff of the budget meter + controls. The live month-to-date value
  // is masked by shotOptions (it changes with real usage).
  const spendCard = win.locator('.spend-cap');
  await expect(spendCard).toBeVisible();
  await expect(spendCard).toHaveScreenshot('spend-cap.png', shotOptions(win));
});

test('Workspace preview surface (per-video, <video> masked)', async () => {
  // Back to Library, open the seeded sample into its Workspace.
  await openTopTab(win, 'Library');
  await openVideo(win, 'sample');
  await expect(win.locator('.workspace')).toBeVisible();
  // The <video> frame (moving testsrc) is masked by shotOptions; the chrome
  // around the preview — player controls, tab strip, panels — is the baseline.
  await expect(win).toHaveScreenshot('workspace-preview.png', shotOptions(win));
});
